// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.nio.ByteBuffer

#ifndef java_nio_ByteBuffer_JNI
#define java_nio_ByteBuffer_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "ByteBuffer_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Class Accessors
#ifndef java_nio_ByteBuffer_clazz_defined
#define java_nio_ByteBuffer_clazz_defined
inline jclass java_nio_ByteBuffer_clazz(JNIEnv* env) {
  static const char kClassName[] = "java.nio.ByteBuffer";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace JNI_ByteBuffer {

// Native to Java functions
[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_Constructor(
    JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "()V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_alignedSlice(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "alignedSlice",
      "(I)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), as_jint(p0));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static int32_t Java_ByteBuffer_alignmentOffset(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "alignmentOffset",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jbyteArray> Java_ByteBuffer_array(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "array",
      "()[B",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jbyteArray _ret2 = static_cast<jbyteArray>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jbyteArray>::Adopt(env, _ret2);
}

[[maybe_unused]] static int32_t Java_ByteBuffer_arrayOffset(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "arrayOffset",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_asCharBuffer(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "asCharBuffer",
      "()Ljava/nio/CharBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_asDoubleBuffer(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "asDoubleBuffer",
      "()Ljava/nio/DoubleBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_asFloatBuffer(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "asFloatBuffer",
      "()Ljava/nio/FloatBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_asIntBuffer(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "asIntBuffer",
      "()Ljava/nio/IntBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_asLongBuffer(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "asLongBuffer",
      "()Ljava/nio/LongBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_asReadOnlyBuffer(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "asReadOnlyBuffer",
      "()Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_asShortBuffer(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "asShortBuffer",
      "()Ljava/nio/ShortBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_clear(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "clear",
      "()Ljava/nio/Buffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_compact(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compact",
      "()Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static int32_t Java_ByteBuffer_compareTo__Object(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Object;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static int32_t Java_ByteBuffer_compareTo__ByteBuffer(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/nio/ByteBuffer;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_duplicate(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "duplicate",
      "()Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static bool Java_ByteBuffer_equals(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "equals",
      "(Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_flip(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "flip",
      "()Ljava/nio/Buffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static int8_t Java_ByteBuffer_get(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "get",
      "()B",
      &cached_method_id);
  auto _ret = env->CallByteMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int8_t Java_ByteBuffer_get__int(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "get",
      "(I)B",
      &cached_method_id);
  auto _ret = env->CallByteMethod(obj.obj(), call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_get(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0,
    const ::jni_zero::JavaRef<jbyteArray>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "get",
      "(I[B)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), as_jint(p0), p1.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_get(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0,
    const ::jni_zero::JavaRef<jbyteArray>& p1,
    JniIntWrapper p2,
    JniIntWrapper p3) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "get",
      "(I[BII)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(
      obj.obj(),
      call_context.method_id(),
      as_jint(p0),
      p1.obj(),
      as_jint(p2),
      as_jint(p3));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_get__byteArray(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jbyteArray>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "get",
      "([B)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_get(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jbyteArray>& p0,
    JniIntWrapper p1,
    JniIntWrapper p2) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "get",
      "([BII)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(
      obj.obj(),
      call_context.method_id(),
      p0.obj(),
      as_jint(p1),
      as_jint(p2));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static uint16_t Java_ByteBuffer_getChar(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getChar",
      "()C",
      &cached_method_id);
  auto _ret = env->CallCharMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static uint16_t Java_ByteBuffer_getChar(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getChar",
      "(I)C",
      &cached_method_id);
  auto _ret = env->CallCharMethod(obj.obj(), call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static double Java_ByteBuffer_getDouble(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getDouble",
      "()D",
      &cached_method_id);
  auto _ret = env->CallDoubleMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static double Java_ByteBuffer_getDouble(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getDouble",
      "(I)D",
      &cached_method_id);
  auto _ret = env->CallDoubleMethod(obj.obj(), call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static float Java_ByteBuffer_getFloat(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getFloat",
      "()F",
      &cached_method_id);
  auto _ret = env->CallFloatMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static float Java_ByteBuffer_getFloat(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getFloat",
      "(I)F",
      &cached_method_id);
  auto _ret = env->CallFloatMethod(obj.obj(), call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static int32_t Java_ByteBuffer_getInt(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getInt",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int32_t Java_ByteBuffer_getInt(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getInt",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static int64_t Java_ByteBuffer_getLong(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getLong",
      "()J",
      &cached_method_id);
  auto _ret = env->CallLongMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int64_t Java_ByteBuffer_getLong(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getLong",
      "(I)J",
      &cached_method_id);
  auto _ret = env->CallLongMethod(obj.obj(), call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static int16_t Java_ByteBuffer_getShort(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getShort",
      "()S",
      &cached_method_id);
  auto _ret = env->CallShortMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int16_t Java_ByteBuffer_getShort(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getShort",
      "(I)S",
      &cached_method_id);
  auto _ret = env->CallShortMethod(obj.obj(), call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static bool Java_ByteBuffer_hasArray(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "hasArray",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int32_t Java_ByteBuffer_hashCode(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "hashCode",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static bool Java_ByteBuffer_isDirect(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "isDirect",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_limit(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "limit",
      "(I)Ljava/nio/Buffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), as_jint(p0));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_mark(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "mark",
      "()Ljava/nio/Buffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static int32_t Java_ByteBuffer_mismatch(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "mismatch",
      "(Ljava/nio/ByteBuffer;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_order(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "order",
      "(Ljava/nio/ByteOrder;)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_order(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "order",
      "()Ljava/nio/ByteOrder;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_position(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "position",
      "(I)Ljava/nio/Buffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), as_jint(p0));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_put__byte(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    int8_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "put",
      "(B)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_put__int__byte(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0,
    int8_t p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "put",
      "(IB)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), as_jint(p0), p1);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_put__int__byteArray(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0,
    const ::jni_zero::JavaRef<jbyteArray>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "put",
      "(I[B)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), as_jint(p0), p1.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_put__int__byteArray__int__int(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0,
    const ::jni_zero::JavaRef<jbyteArray>& p1,
    JniIntWrapper p2,
    JniIntWrapper p3) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "put",
      "(I[BII)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(
      obj.obj(),
      call_context.method_id(),
      as_jint(p0),
      p1.obj(),
      as_jint(p2),
      as_jint(p3));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_put__int__ByteBuffer__int__int(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0,
    const ::jni_zero::JavaRef<jobject>& p1,
    JniIntWrapper p2,
    JniIntWrapper p3) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "put",
      "(ILjava/nio/ByteBuffer;II)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(
      obj.obj(),
      call_context.method_id(),
      as_jint(p0),
      p1.obj(),
      as_jint(p2),
      as_jint(p3));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_put__byteArray(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jbyteArray>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "put",
      "([B)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_put(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jbyteArray>& p0,
    JniIntWrapper p1,
    JniIntWrapper p2) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "put",
      "([BII)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(
      obj.obj(),
      call_context.method_id(),
      p0.obj(),
      as_jint(p1),
      as_jint(p2));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_put__ByteBuffer(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "put",
      "(Ljava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_putChar(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    uint16_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "putChar",
      "(C)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_putChar(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0,
    uint16_t p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "putChar",
      "(IC)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), as_jint(p0), p1);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_putDouble(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    double p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "putDouble",
      "(D)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_putDouble(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0,
    double p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "putDouble",
      "(ID)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), as_jint(p0), p1);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_putFloat(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    float p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "putFloat",
      "(F)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_putFloat(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0,
    float p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "putFloat",
      "(IF)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), as_jint(p0), p1);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_putInt(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "putInt",
      "(I)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), as_jint(p0));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_putInt(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "putInt",
      "(II)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), as_jint(p0), as_jint(p1));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_putLong(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0,
    int64_t p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "putLong",
      "(IJ)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), as_jint(p0), p1);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_putLong(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "putLong",
      "(J)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_putShort(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0,
    int16_t p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "putShort",
      "(IS)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), as_jint(p0), p1);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_putShort(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    int16_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "putShort",
      "(S)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_reset(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "reset",
      "()Ljava/nio/Buffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_rewind(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "rewind",
      "()Ljava/nio/Buffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_slice(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "slice",
      "()Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_slice(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "slice",
      "(II)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), as_jint(p0), as_jint(p1));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_ByteBuffer_toString(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "toString",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_allocate(
    JNIEnv* env,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "allocate",
      "(I)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(p0));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_allocateDirect(
    JNIEnv* env,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "allocateDirect",
      "(I)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(p0));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_wrap(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jbyteArray>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "wrap",
      "([B)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ByteBuffer_wrap(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jbyteArray>& p0,
    JniIntWrapper p1,
    JniIntWrapper p2) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_nio_ByteBuffer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "wrap",
      "([BII)Ljava/nio/ByteBuffer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      as_jint(p1),
      as_jint(p2));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace JNI_ByteBuffer

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::JNI_ByteBuffer;

template<>
class _CalledByNativesStatics<::java::nio::JByteBuffer> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> New(JNIEnv* env) {
    return Java_ByteBuffer_Constructor(env)
        .As<::java::nio::JByteBuffer>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> allocate(
      JNIEnv* env,
      JniIntWrapper p0) {
    return Java_ByteBuffer_allocate(env, p0)
        .As<::java::nio::JByteBuffer>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> allocateDirect(
      JNIEnv* env,
      JniIntWrapper p0) {
    return Java_ByteBuffer_allocateDirect(env, p0)
        .As<::java::nio::JByteBuffer>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> wrap(
      JNIEnv* env,
      const ::jni_zero::JavaRef<JArray<int8_t>>& p0) {
    return Java_ByteBuffer_wrap(env, p0)
        .As<::java::nio::JByteBuffer>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> wrap(
      JNIEnv* env,
      const ::jni_zero::JavaRef<JArray<int8_t>>& p0,
      JniIntWrapper p1,
      JniIntWrapper p2) {
    return Java_ByteBuffer_wrap(env, p0, p1, p2)
        .As<::java::nio::JByteBuffer>();
  }

};

template<>
class _CalledByNatives<::java::nio::JByteBuffer> {
  public:
  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> alignedSlice(
      JNIEnv* env,
      JniIntWrapper p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_alignedSlice(env, *this_obj, p0)
        .As<::java::nio::JByteBuffer>();
  }

  int32_t alignmentOffset(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_alignmentOffset(env, *this_obj, p0, p1);
  }

  ::jni_zero::ScopedJavaLocalRef<JArray<int8_t>> array(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_array(env, *this_obj)
        .As<JArray<int8_t>>();
  }

  int32_t arrayOffset(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_arrayOffset(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JCharBuffer> asCharBuffer(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_asCharBuffer(env, *this_obj)
        .As<::java::nio::JCharBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JDoubleBuffer> asDoubleBuffer(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_asDoubleBuffer(env, *this_obj)
        .As<::java::nio::JDoubleBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JFloatBuffer> asFloatBuffer(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_asFloatBuffer(env, *this_obj)
        .As<::java::nio::JFloatBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JIntBuffer> asIntBuffer(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_asIntBuffer(env, *this_obj)
        .As<::java::nio::JIntBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JLongBuffer> asLongBuffer(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_asLongBuffer(env, *this_obj)
        .As<::java::nio::JLongBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> asReadOnlyBuffer(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_asReadOnlyBuffer(env, *this_obj)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JShortBuffer> asShortBuffer(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_asShortBuffer(env, *this_obj)
        .As<::java::nio::JShortBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JBuffer> clear(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_clear(env, *this_obj)
        .As<::java::nio::JBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> compact(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_compact(env, *this_obj)
        .As<::java::nio::JByteBuffer>();
  }

  int32_t compareTo(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_compareTo__Object(env, *this_obj, p0);
  }

  int32_t compareTo(JNIEnv* env, const ::jni_zero::JavaRef<::java::nio::JByteBuffer>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_compareTo__ByteBuffer(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> duplicate(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_duplicate(env, *this_obj)
        .As<::java::nio::JByteBuffer>();
  }

  bool equals(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_equals(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JBuffer> flip(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_flip(env, *this_obj)
        .As<::java::nio::JBuffer>();
  }

  int8_t get(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_get(env, *this_obj);
  }

  int8_t get(JNIEnv* env, JniIntWrapper p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_get__int(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> get(
      JNIEnv* env,
      JniIntWrapper p0,
      const ::jni_zero::JavaRef<JArray<int8_t>>& p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_get(env, *this_obj, p0, p1)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> get(
      JNIEnv* env,
      JniIntWrapper p0,
      const ::jni_zero::JavaRef<JArray<int8_t>>& p1,
      JniIntWrapper p2,
      JniIntWrapper p3) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_get(env, *this_obj, p0, p1, p2, p3)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> get(
      JNIEnv* env,
      const ::jni_zero::JavaRef<JArray<int8_t>>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_get__byteArray(env, *this_obj, p0)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> get(
      JNIEnv* env,
      const ::jni_zero::JavaRef<JArray<int8_t>>& p0,
      JniIntWrapper p1,
      JniIntWrapper p2) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_get(env, *this_obj, p0, p1, p2)
        .As<::java::nio::JByteBuffer>();
  }

  uint16_t getChar(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_getChar(env, *this_obj);
  }

  uint16_t getChar(JNIEnv* env, JniIntWrapper p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_getChar(env, *this_obj, p0);
  }

  double getDouble(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_getDouble(env, *this_obj);
  }

  double getDouble(JNIEnv* env, JniIntWrapper p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_getDouble(env, *this_obj, p0);
  }

  float getFloat(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_getFloat(env, *this_obj);
  }

  float getFloat(JNIEnv* env, JniIntWrapper p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_getFloat(env, *this_obj, p0);
  }

  int32_t getInt(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_getInt(env, *this_obj);
  }

  int32_t getInt(JNIEnv* env, JniIntWrapper p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_getInt(env, *this_obj, p0);
  }

  int64_t getLong(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_getLong(env, *this_obj);
  }

  int64_t getLong(JNIEnv* env, JniIntWrapper p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_getLong(env, *this_obj, p0);
  }

  int16_t getShort(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_getShort(env, *this_obj);
  }

  int16_t getShort(JNIEnv* env, JniIntWrapper p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_getShort(env, *this_obj, p0);
  }

  bool hasArray(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_hasArray(env, *this_obj);
  }

  int32_t hashCode(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_hashCode(env, *this_obj);
  }

  bool isDirect(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_isDirect(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JBuffer> limit(JNIEnv* env, JniIntWrapper p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_limit(env, *this_obj, p0)
        .As<::java::nio::JBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JBuffer> mark(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_mark(env, *this_obj)
        .As<::java::nio::JBuffer>();
  }

  int32_t mismatch(JNIEnv* env, const ::jni_zero::JavaRef<::java::nio::JByteBuffer>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_mismatch(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> order(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::nio::JByteOrder>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_order(env, *this_obj, p0)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteOrder> order(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_order(env, *this_obj)
        .As<::java::nio::JByteOrder>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JBuffer> position(JNIEnv* env, JniIntWrapper p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_position(env, *this_obj, p0)
        .As<::java::nio::JBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> put(JNIEnv* env, int8_t p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_put__byte(env, *this_obj, p0)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> put(
      JNIEnv* env,
      JniIntWrapper p0,
      int8_t p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_put__int__byte(env, *this_obj, p0, p1)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> put(
      JNIEnv* env,
      JniIntWrapper p0,
      const ::jni_zero::JavaRef<JArray<int8_t>>& p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_put__int__byteArray(env, *this_obj, p0, p1)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> put(
      JNIEnv* env,
      JniIntWrapper p0,
      const ::jni_zero::JavaRef<JArray<int8_t>>& p1,
      JniIntWrapper p2,
      JniIntWrapper p3) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_put__int__byteArray__int__int(env, *this_obj, p0, p1, p2, p3)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> put(
      JNIEnv* env,
      JniIntWrapper p0,
      const ::jni_zero::JavaRef<::java::nio::JByteBuffer>& p1,
      JniIntWrapper p2,
      JniIntWrapper p3) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_put__int__ByteBuffer__int__int(env, *this_obj, p0, p1, p2, p3)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> put(
      JNIEnv* env,
      const ::jni_zero::JavaRef<JArray<int8_t>>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_put__byteArray(env, *this_obj, p0)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> put(
      JNIEnv* env,
      const ::jni_zero::JavaRef<JArray<int8_t>>& p0,
      JniIntWrapper p1,
      JniIntWrapper p2) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_put(env, *this_obj, p0, p1, p2)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> put(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::nio::JByteBuffer>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_put__ByteBuffer(env, *this_obj, p0)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> putChar(JNIEnv* env, uint16_t p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_putChar(env, *this_obj, p0)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> putChar(
      JNIEnv* env,
      JniIntWrapper p0,
      uint16_t p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_putChar(env, *this_obj, p0, p1)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> putDouble(JNIEnv* env, double p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_putDouble(env, *this_obj, p0)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> putDouble(
      JNIEnv* env,
      JniIntWrapper p0,
      double p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_putDouble(env, *this_obj, p0, p1)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> putFloat(JNIEnv* env, float p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_putFloat(env, *this_obj, p0)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> putFloat(
      JNIEnv* env,
      JniIntWrapper p0,
      float p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_putFloat(env, *this_obj, p0, p1)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> putInt(JNIEnv* env, JniIntWrapper p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_putInt(env, *this_obj, p0)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> putInt(
      JNIEnv* env,
      JniIntWrapper p0,
      JniIntWrapper p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_putInt(env, *this_obj, p0, p1)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> putLong(
      JNIEnv* env,
      JniIntWrapper p0,
      int64_t p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_putLong(env, *this_obj, p0, p1)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> putLong(JNIEnv* env, int64_t p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_putLong(env, *this_obj, p0)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> putShort(
      JNIEnv* env,
      JniIntWrapper p0,
      int16_t p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_putShort(env, *this_obj, p0, p1)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> putShort(JNIEnv* env, int16_t p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_putShort(env, *this_obj, p0)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JBuffer> reset(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_reset(env, *this_obj)
        .As<::java::nio::JBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JBuffer> rewind(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_rewind(env, *this_obj)
        .As<::java::nio::JBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> slice(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_slice(env, *this_obj)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::nio::JByteBuffer> slice(
      JNIEnv* env,
      JniIntWrapper p0,
      JniIntWrapper p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_slice(env, *this_obj, p0, p1)
        .As<::java::nio::JByteBuffer>();
  }

  ::jni_zero::ScopedJavaLocalRef<jstring> toString(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::nio::JByteBuffer>*>(this);
    return Java_ByteBuffer_toString(env, *this_obj);
  }

};


}  // namespace jni_zero_internal

namespace java::nio {
using ByteBufferJni = ::jni_zero_internal::_CalledByNativesStatics<::java::nio::JByteBuffer>;
}
#ifndef _JNI_ZERO_ByteBufferJni_DEFINED
#define _JNI_ZERO_ByteBufferJni_DEFINED
using ::java::nio::ByteBufferJni;
#endif


#pragma clang diagnostic pop
#endif  // java_nio_ByteBuffer_JNI
