// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.nio.ByteBuffer

#ifndef java_nio_ByteBuffer_SHARED_JNI
#define java_nio_ByteBuffer_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_nio_JBuffer_DEFINED
#define _JNI_ZERO_java_nio_JBuffer_DEFINED
namespace java::nio {
class _JBuffer : public _jobject {};
using JBuffer = _JBuffer*;
}
#endif

#ifndef _JNI_ZERO_JBuffer_DEFINED
#define _JNI_ZERO_JBuffer_DEFINED
using ::java::nio::JBuffer;
#endif

#ifndef _JNI_ZERO_java_nio_JByteBuffer_DEFINED
#define _JNI_ZERO_java_nio_JByteBuffer_DEFINED
namespace java::nio {
class _JByteBuffer : public _jobject {};
using JByteBuffer = _JByteBuffer*;
}
#endif

#ifndef _JNI_ZERO_JByteBuffer_DEFINED
#define _JNI_ZERO_JByteBuffer_DEFINED
using ::java::nio::JByteBuffer;
#endif

#ifndef _JNI_ZERO_java_nio_JByteOrder_DEFINED
#define _JNI_ZERO_java_nio_JByteOrder_DEFINED
namespace java::nio {
class _JByteOrder : public _jobject {};
using JByteOrder = _JByteOrder*;
}
#endif

#ifndef _JNI_ZERO_JByteOrder_DEFINED
#define _JNI_ZERO_JByteOrder_DEFINED
using ::java::nio::JByteOrder;
#endif

#ifndef _JNI_ZERO_java_nio_JCharBuffer_DEFINED
#define _JNI_ZERO_java_nio_JCharBuffer_DEFINED
namespace java::nio {
class _JCharBuffer : public _jobject {};
using JCharBuffer = _JCharBuffer*;
}
#endif

#ifndef _JNI_ZERO_JCharBuffer_DEFINED
#define _JNI_ZERO_JCharBuffer_DEFINED
using ::java::nio::JCharBuffer;
#endif

#ifndef _JNI_ZERO_java_nio_JDoubleBuffer_DEFINED
#define _JNI_ZERO_java_nio_JDoubleBuffer_DEFINED
namespace java::nio {
class _JDoubleBuffer : public _jobject {};
using JDoubleBuffer = _JDoubleBuffer*;
}
#endif

#ifndef _JNI_ZERO_JDoubleBuffer_DEFINED
#define _JNI_ZERO_JDoubleBuffer_DEFINED
using ::java::nio::JDoubleBuffer;
#endif

#ifndef _JNI_ZERO_java_nio_JFloatBuffer_DEFINED
#define _JNI_ZERO_java_nio_JFloatBuffer_DEFINED
namespace java::nio {
class _JFloatBuffer : public _jobject {};
using JFloatBuffer = _JFloatBuffer*;
}
#endif

#ifndef _JNI_ZERO_JFloatBuffer_DEFINED
#define _JNI_ZERO_JFloatBuffer_DEFINED
using ::java::nio::JFloatBuffer;
#endif

#ifndef _JNI_ZERO_java_nio_JIntBuffer_DEFINED
#define _JNI_ZERO_java_nio_JIntBuffer_DEFINED
namespace java::nio {
class _JIntBuffer : public _jobject {};
using JIntBuffer = _JIntBuffer*;
}
#endif

#ifndef _JNI_ZERO_JIntBuffer_DEFINED
#define _JNI_ZERO_JIntBuffer_DEFINED
using ::java::nio::JIntBuffer;
#endif

#ifndef _JNI_ZERO_java_nio_JLongBuffer_DEFINED
#define _JNI_ZERO_java_nio_JLongBuffer_DEFINED
namespace java::nio {
class _JLongBuffer : public _jobject {};
using JLongBuffer = _JLongBuffer*;
}
#endif

#ifndef _JNI_ZERO_JLongBuffer_DEFINED
#define _JNI_ZERO_JLongBuffer_DEFINED
using ::java::nio::JLongBuffer;
#endif

#ifndef _JNI_ZERO_java_nio_JShortBuffer_DEFINED
#define _JNI_ZERO_java_nio_JShortBuffer_DEFINED
namespace java::nio {
class _JShortBuffer : public _jobject {};
using JShortBuffer = _JShortBuffer*;
}
#endif

#ifndef _JNI_ZERO_JShortBuffer_DEFINED
#define _JNI_ZERO_JShortBuffer_DEFINED
using ::java::nio::JShortBuffer;
#endif


#endif  // java_nio_ByteBuffer_SHARED_JNI
