// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.ClassLoader

#ifndef java_lang_ClassLoader_JNI
#define java_lang_ClassLoader_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "ClassLoader_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
namespace JNI_ClassLoader {

// Native to Java functions
[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ClassLoader_Constructor(
    JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "()V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ClassLoader_Constructor(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/lang/ClassLoader;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static void Java_ClassLoader_clearAssertionStatus(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "clearAssertionStatus",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jclass> Java_ClassLoader_defineClass__byteArray__int__int(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jbyteArray>& p0,
    JniIntWrapper p1,
    JniIntWrapper p2) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "defineClass",
      "([BII)Ljava/lang/Class;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(
      obj.obj(),
      call_context.method_id(),
      p0.obj(),
      as_jint(p1),
      as_jint(p2));
  jclass _ret2 = static_cast<jclass>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jclass>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jclass> Java_ClassLoader_defineClass(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0,
    const ::jni_zero::JavaRef<jbyteArray>& p1,
    JniIntWrapper p2,
    JniIntWrapper p3) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "defineClass",
      "(Ljava/lang/String;[BII)Ljava/lang/Class;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(
      obj.obj(),
      call_context.method_id(),
      p0.obj(),
      p1.obj(),
      as_jint(p2),
      as_jint(p3));
  jclass _ret2 = static_cast<jclass>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jclass>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jclass> Java_ClassLoader_defineClass(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0,
    const ::jni_zero::JavaRef<jbyteArray>& p1,
    JniIntWrapper p2,
    JniIntWrapper p3,
    const ::jni_zero::JavaRef<jobject>& p4) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "defineClass",
      "(Ljava/lang/String;[BIILjava/security/ProtectionDomain;)Ljava/lang/Class;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(
      obj.obj(),
      call_context.method_id(),
      p0.obj(),
      p1.obj(),
      as_jint(p2),
      as_jint(p3),
      p4.obj());
  jclass _ret2 = static_cast<jclass>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jclass>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jclass> Java_ClassLoader_defineClass__String__java_nio_ByteBuffer__java_security_ProtectionDomain(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0,
    const ::jni_zero::JavaRef<jobject>& p1,
    const ::jni_zero::JavaRef<jobject>& p2) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "defineClass",
      "(Ljava/lang/String;Ljava/nio/ByteBuffer;Ljava/security/ProtectionDomain;)Ljava/lang/Class;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(
      obj.obj(),
      call_context.method_id(),
      p0.obj(),
      p1.obj(),
      p2.obj());
  jclass _ret2 = static_cast<jclass>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jclass>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ClassLoader_definePackage(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0,
    const ::jni_zero::JavaRef<jstring>& p1,
    const ::jni_zero::JavaRef<jstring>& p2,
    const ::jni_zero::JavaRef<jstring>& p3,
    const ::jni_zero::JavaRef<jstring>& p4,
    const ::jni_zero::JavaRef<jstring>& p5,
    const ::jni_zero::JavaRef<jstring>& p6,
    const ::jni_zero::JavaRef<jobject>& p7) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "definePackage",
      "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/net/URL;)Ljava/lang/Package;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(
      obj.obj(),
      call_context.method_id(),
      p0.obj(),
      p1.obj(),
      p2.obj(),
      p3.obj(),
      p4.obj(),
      p5.obj(),
      p6.obj(),
      p7.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jclass> Java_ClassLoader_findClass(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "findClass",
      "(Ljava/lang/String;)Ljava/lang/Class;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  jclass _ret2 = static_cast<jclass>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jclass>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_ClassLoader_findLibrary(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "findLibrary",
      "(Ljava/lang/String;)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jclass> Java_ClassLoader_findLoadedClass(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "findLoadedClass",
      "(Ljava/lang/String;)Ljava/lang/Class;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  jclass _ret2 = static_cast<jclass>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jclass>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ClassLoader_findResource(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "findResource",
      "(Ljava/lang/String;)Ljava/net/URL;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ClassLoader_findResources(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "findResources",
      "(Ljava/lang/String;)Ljava/util/Enumeration;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jclass> Java_ClassLoader_findSystemClass(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "findSystemClass",
      "(Ljava/lang/String;)Ljava/lang/Class;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  jclass _ret2 = static_cast<jclass>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jclass>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ClassLoader_getPackage(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getPackage",
      "(Ljava/lang/String;)Ljava/lang/Package;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobjectArray> Java_ClassLoader_getPackages(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getPackages",
      "()[Ljava/lang/Package;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jobjectArray _ret2 = static_cast<jobjectArray>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jobjectArray>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ClassLoader_getParent(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getParent",
      "()Ljava/lang/ClassLoader;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ClassLoader_getResource(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getResource",
      "(Ljava/lang/String;)Ljava/net/URL;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ClassLoader_getResourceAsStream(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getResourceAsStream",
      "(Ljava/lang/String;)Ljava/io/InputStream;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ClassLoader_getResources(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getResources",
      "(Ljava/lang/String;)Ljava/util/Enumeration;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jclass> Java_ClassLoader_loadClass(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "loadClass",
      "(Ljava/lang/String;)Ljava/lang/Class;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  jclass _ret2 = static_cast<jclass>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jclass>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jclass> Java_ClassLoader_loadClass(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0,
    bool p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "loadClass",
      "(Ljava/lang/String;Z)Ljava/lang/Class;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj(), p1);
  jclass _ret2 = static_cast<jclass>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jclass>::Adopt(env, _ret2);
}

[[maybe_unused]] static void Java_ClassLoader_resolveClass(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jclass>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "resolveClass",
      "(Ljava/lang/Class;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0.obj());
}

[[maybe_unused]] static void Java_ClassLoader_setClassAssertionStatus(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0,
    bool p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "setClassAssertionStatus",
      "(Ljava/lang/String;Z)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0.obj(), p1);
}

[[maybe_unused]] static void Java_ClassLoader_setDefaultAssertionStatus(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    bool p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "setDefaultAssertionStatus",
      "(Z)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0);
}

[[maybe_unused]] static void Java_ClassLoader_setPackageAssertionStatus(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jstring>& p0,
    bool p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "setPackageAssertionStatus",
      "(Ljava/lang/String;Z)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0.obj(), p1);
}

[[maybe_unused]] static void Java_ClassLoader_setSigners(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jclass>& p0,
    const ::jni_zero::JavaRef<jobjectArray>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "setSigners",
      "(Ljava/lang/Class;[Ljava/lang/Object;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0.obj(), p1.obj());
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ClassLoader_getSystemClassLoader(
    JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getSystemClassLoader",
      "()Ljava/lang/ClassLoader;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ClassLoader_getSystemResource(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getSystemResource",
      "(Ljava/lang/String;)Ljava/net/URL;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ClassLoader_getSystemResourceAsStream(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getSystemResourceAsStream",
      "(Ljava/lang/String;)Ljava/io/InputStream;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_ClassLoader_getSystemResources(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getSystemResources",
      "(Ljava/lang/String;)Ljava/util/Enumeration;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static bool Java_ClassLoader_registerAsParallelCapable(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_class_loader_class;
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<false> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "registerAsParallelCapable",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id());
  return _ret;
}



}  // namespace JNI_ClassLoader

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::JNI_ClassLoader;

template<>
class _CalledByNativesStatics<::java::lang::JClassLoader> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JClassLoader> New(JNIEnv* env) {
    return Java_ClassLoader_Constructor(env)
        .As<::java::lang::JClassLoader>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JClassLoader> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::lang::JClassLoader>& p0) {
    return Java_ClassLoader_Constructor(env, p0)
        .As<::java::lang::JClassLoader>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JClassLoader> getSystemClassLoader(
      JNIEnv* env) {
    return Java_ClassLoader_getSystemClassLoader(env)
        .As<::java::lang::JClassLoader>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::net::JURL> getSystemResource(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_ClassLoader_getSystemResource(env, p0)
        .As<::java::net::JURL>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::io::JInputStream> getSystemResourceAsStream(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_ClassLoader_getSystemResourceAsStream(env, p0)
        .As<::java::io::JInputStream>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::util::JEnumeration<::java::net::JURL>> getSystemResources(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_ClassLoader_getSystemResources(env, p0)
        .As<::java::util::JEnumeration<::java::net::JURL>>();
  }

  static bool registerAsParallelCapable(JNIEnv* env) {
    return Java_ClassLoader_registerAsParallelCapable(env);
  }

};

template<>
class _CalledByNatives<::java::lang::JClassLoader> {
  public:
  void clearAssertionStatus(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    Java_ClassLoader_clearAssertionStatus(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<jclass> defineClass(
      JNIEnv* env,
      const ::jni_zero::JavaRef<JArray<int8_t>>& p0,
      JniIntWrapper p1,
      JniIntWrapper p2) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_defineClass__byteArray__int__int(env, *this_obj, p0, p1, p2);
  }

  ::jni_zero::ScopedJavaLocalRef<jclass> defineClass(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0,
      const ::jni_zero::JavaRef<JArray<int8_t>>& p1,
      JniIntWrapper p2,
      JniIntWrapper p3) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_defineClass(env, *this_obj, p0, p1, p2, p3);
  }

  ::jni_zero::ScopedJavaLocalRef<jclass> defineClass(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0,
      const ::jni_zero::JavaRef<JArray<int8_t>>& p1,
      JniIntWrapper p2,
      JniIntWrapper p3,
      const ::jni_zero::JavaRef<::java::security::JProtectionDomain>& p4) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_defineClass(env, *this_obj, p0, p1, p2, p3, p4);
  }

  ::jni_zero::ScopedJavaLocalRef<jclass> defineClass(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0,
      const ::jni_zero::JavaRef<::java::nio::JByteBuffer>& p1,
      const ::jni_zero::JavaRef<::java::security::JProtectionDomain>& p2) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_defineClass__String__java_nio_ByteBuffer__java_security_ProtectionDomain(
        env,
        *this_obj,
        p0,
        p1,
        p2);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::lang::JPackage> definePackage(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0,
      const ::jni_zero::JavaRef<jstring>& p1,
      const ::jni_zero::JavaRef<jstring>& p2,
      const ::jni_zero::JavaRef<jstring>& p3,
      const ::jni_zero::JavaRef<jstring>& p4,
      const ::jni_zero::JavaRef<jstring>& p5,
      const ::jni_zero::JavaRef<jstring>& p6,
      const ::jni_zero::JavaRef<::java::net::JURL>& p7) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_definePackage(env, *this_obj, p0, p1, p2, p3, p4, p5, p6, p7)
        .As<::java::lang::JPackage>();
  }

  ::jni_zero::ScopedJavaLocalRef<jclass> findClass(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_findClass(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<jstring> findLibrary(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_findLibrary(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<jclass> findLoadedClass(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_findLoadedClass(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::net::JURL> findResource(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_findResource(env, *this_obj, p0)
        .As<::java::net::JURL>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JEnumeration<::java::net::JURL>> findResources(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_findResources(env, *this_obj, p0)
        .As<::java::util::JEnumeration<::java::net::JURL>>();
  }

  ::jni_zero::ScopedJavaLocalRef<jclass> findSystemClass(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_findSystemClass(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::lang::JPackage> getPackage(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_getPackage(env, *this_obj, p0)
        .As<::java::lang::JPackage>();
  }

  ::jni_zero::ScopedJavaLocalRef<JArray<::java::lang::JPackage>> getPackages(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_getPackages(env, *this_obj)
        .As<JArray<::java::lang::JPackage>>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::lang::JClassLoader> getParent(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_getParent(env, *this_obj)
        .As<::java::lang::JClassLoader>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::net::JURL> getResource(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_getResource(env, *this_obj, p0)
        .As<::java::net::JURL>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::io::JInputStream> getResourceAsStream(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_getResourceAsStream(env, *this_obj, p0)
        .As<::java::io::JInputStream>();
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JEnumeration<::java::net::JURL>> getResources(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_getResources(env, *this_obj, p0)
        .As<::java::util::JEnumeration<::java::net::JURL>>();
  }

  ::jni_zero::ScopedJavaLocalRef<jclass> loadClass(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_loadClass(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<jclass> loadClass(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0,
      bool p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    return Java_ClassLoader_loadClass(env, *this_obj, p0, p1);
  }

  void resolveClass(JNIEnv* env, const ::jni_zero::JavaRef<jclass>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    Java_ClassLoader_resolveClass(env, *this_obj, p0);
  }

  void setClassAssertionStatus(JNIEnv* env, const ::jni_zero::JavaRef<jstring>& p0, bool p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    Java_ClassLoader_setClassAssertionStatus(env, *this_obj, p0, p1);
  }

  void setDefaultAssertionStatus(JNIEnv* env, bool p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    Java_ClassLoader_setDefaultAssertionStatus(env, *this_obj, p0);
  }

  void setPackageAssertionStatus(JNIEnv* env, const ::jni_zero::JavaRef<jstring>& p0, bool p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    Java_ClassLoader_setPackageAssertionStatus(env, *this_obj, p0, p1);
  }

  void setSigners(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jclass>& p0,
      const ::jni_zero::JavaRef<JArray<jobject>>& p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JClassLoader>*>(this);
    Java_ClassLoader_setSigners(env, *this_obj, p0, p1);
  }

};


}  // namespace jni_zero_internal

namespace java::lang {
using ClassLoaderJni = ::jni_zero_internal::_CalledByNativesStatics<::java::lang::JClassLoader>;
}
#ifndef _JNI_ZERO_ClassLoaderJni_DEFINED
#define _JNI_ZERO_ClassLoaderJni_DEFINED
using ::java::lang::ClassLoaderJni;
#endif


#pragma clang diagnostic pop
#endif  // java_lang_ClassLoader_JNI
