// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.ClassLoader

#ifndef java_lang_ClassLoader_SHARED_JNI
#define java_lang_ClassLoader_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_io_JInputStream_DEFINED
#define _JNI_ZERO_java_io_JInputStream_DEFINED
namespace java::io {
class _JInputStream : public _jobject {};
using JInputStream = _JInputStream*;
}
#endif

#ifndef _JNI_ZERO_JInputStream_DEFINED
#define _JNI_ZERO_JInputStream_DEFINED
using ::java::io::JInputStream;
#endif

#ifndef _JNI_ZERO_java_lang_JClassLoader_DEFINED
#define _JNI_ZERO_java_lang_JClassLoader_DEFINED
namespace java::lang {
class _JClassLoader : public _jobject {};
using JClassLoader = _JClassLoader*;
}
#endif

#ifndef _JNI_ZERO_JClassLoader_DEFINED
#define _JNI_ZERO_JClassLoader_DEFINED
using ::java::lang::JClassLoader;
#endif

#ifndef _JNI_ZERO_java_lang_JPackage_DEFINED
#define _JNI_ZERO_java_lang_JPackage_DEFINED
namespace java::lang {
class _JPackage : public _jobject {};
using JPackage = _JPackage*;
}
#endif

#ifndef _JNI_ZERO_JPackage_DEFINED
#define _JNI_ZERO_JPackage_DEFINED
using ::java::lang::JPackage;
#endif

#ifndef _JNI_ZERO_java_net_JURL_DEFINED
#define _JNI_ZERO_java_net_JURL_DEFINED
namespace java::net {
class _JURL : public _jobject {};
using JURL = _JURL*;
}
#endif

#ifndef _JNI_ZERO_JURL_DEFINED
#define _JNI_ZERO_JURL_DEFINED
using ::java::net::JURL;
#endif

#ifndef _JNI_ZERO_java_nio_JByteBuffer_DEFINED
#define _JNI_ZERO_java_nio_JByteBuffer_DEFINED
namespace java::nio {
class _JByteBuffer : public _jobject {};
using JByteBuffer = _JByteBuffer*;
}
#endif

#ifndef _JNI_ZERO_JByteBuffer_DEFINED
#define _JNI_ZERO_JByteBuffer_DEFINED
using ::java::nio::JByteBuffer;
#endif

#ifndef _JNI_ZERO_java_security_JProtectionDomain_DEFINED
#define _JNI_ZERO_java_security_JProtectionDomain_DEFINED
namespace java::security {
class _JProtectionDomain : public _jobject {};
using JProtectionDomain = _JProtectionDomain*;
}
#endif

#ifndef _JNI_ZERO_JProtectionDomain_DEFINED
#define _JNI_ZERO_JProtectionDomain_DEFINED
using ::java::security::JProtectionDomain;
#endif

#ifndef _JNI_ZERO_java_util_JEnumeration_DEFINED
#define _JNI_ZERO_java_util_JEnumeration_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T>
class _JEnumeration : public _jobject {};
template <typename T>
using JEnumeration = _JEnumeration<T>*;
}
#endif

#ifndef _JNI_ZERO_JEnumeration_DEFINED
#define _JNI_ZERO_JEnumeration_DEFINED
using ::java::util::JEnumeration;
#endif


#endif  // java_lang_ClassLoader_SHARED_JNI
