// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.jni_zero.CommonApis

#ifndef org_jni_1zero_CommonApis_SHARED_JNI
#define org_jni_1zero_CommonApis_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_util_JMap_DEFINED
#define _JNI_ZERO_java_util_JMap_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T1, ::jni_zero::internal::IsJobject T2>
class _JMap : public _jobject {};
template <typename T1, typename T2>
using JMap = _JMap<T1, T2>*;
}
#endif

#ifndef _JNI_ZERO_JMap_DEFINED
#define _JNI_ZERO_JMap_DEFINED
using ::java::util::JMap;
#endif

#ifndef _JNI_ZERO_org_jni_zero_JCommonApis_DEFINED
#define _JNI_ZERO_org_jni_zero_JCommonApis_DEFINED
namespace org::jni_zero {
class _JCommonApis : public _jobject {};
using JCommonApis = _JCommonApis*;
}
#endif

#ifndef _JNI_ZERO_JCommonApis_DEFINED
#define _JNI_ZERO_JCommonApis_DEFINED
using ::org::jni_zero::JCommonApis;
#endif


#endif  // org_jni_1zero_CommonApis_SHARED_JNI
