// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.jni_zero.JniPtrImpl

#ifndef org_jni_1zero_JniPtrImpl_SHARED_JNI
#define org_jni_1zero_JniPtrImpl_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_org_jni_zero_JJniPtrImpl_DEFINED
#define _JNI_ZERO_org_jni_zero_JJniPtrImpl_DEFINED
namespace org::jni_zero {
template <::jni_zero::internal::IsJobject T>
class _JJniPtrImpl : public _jobject {};
template <typename T>
using JJniPtrImpl = _JJniPtrImpl<T>*;
}
#endif

#ifndef _JNI_ZERO_JJniPtrImpl_DEFINED
#define _JNI_ZERO_JJniPtrImpl_DEFINED
using ::org::jni_zero::JJniPtrImpl;
#endif

#ifndef _JNI_ZERO_org_jni_zero_JJniTypeToken_DEFINED
#define _JNI_ZERO_org_jni_zero_JJniTypeToken_DEFINED
namespace org::jni_zero {
class _JJniTypeToken : public _jobject {};
using JJniTypeToken = _JJniTypeToken*;
}
#endif

#ifndef _JNI_ZERO_JJniTypeToken_DEFINED
#define _JNI_ZERO_JJniTypeToken_DEFINED
using ::org::jni_zero::JJniTypeToken;
#endif


#endif  // org_jni_1zero_JniPtrImpl_SHARED_JNI
