// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.jni_zero.JniPtrImpl

#ifndef org_jni_1zero_JniPtrImpl_JNI
#define org_jni_1zero_JniPtrImpl_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "JniPtrImpl_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_JniPtrImpl()

// Class Accessors
#ifndef org_jni_1zero_JniPtrImpl_clazz_defined
#define org_jni_1zero_JniPtrImpl_clazz_defined
inline jclass org_jni_1zero_JniPtrImpl_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.jni_zero.JniPtrImpl";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_JniPtrImpl_Constructor(
    JNIEnv* env,
    int64_t nativePtr) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_jni_1zero_JniPtrImpl_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(J)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), nativePtr);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

static void Java_JniPtrImpl_release(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_jni_1zero_JniPtrImpl_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "release",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}


// jobject-subclass-aware definitions:
namespace jni_zero_internal {

template<>
class _CalledByNativesStatics<::org::jni_zero::JJniPtrImpl<jobject>> {
  public:
  template <typename T>
  static ::jni_zero::ScopedJavaLocalRef<::org::jni_zero::JJniPtrImpl<T>> New(
      JNIEnv* env,
      int64_t nativePtr) {
    return Java_JniPtrImpl_Constructor(env, nativePtr)
        .template As<::org::jni_zero::JJniPtrImpl<T>>();
  }

};

template <typename T>
class _CalledByNatives<::org::jni_zero::JJniPtrImpl<T>> {
  public:
  void release(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::org::jni_zero::JJniPtrImpl<T>>*>(this);
    Java_JniPtrImpl_release(env, *this_obj);
  }

};


}  // namespace jni_zero_internal

namespace org::jni_zero {
using JniPtrImplJni = ::jni_zero_internal::_CalledByNativesStatics<::org::jni_zero::JJniPtrImpl<jobject>>;
}
#ifndef _JNI_ZERO_JniPtrImplJni_DEFINED
#define _JNI_ZERO_JniPtrImplJni_DEFINED
using ::org::jni_zero::JniPtrImplJni;
#endif


#pragma clang diagnostic pop
#endif  // org_jni_1zero_JniPtrImpl_JNI
