// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.jni_zero.JniRawPtrImpl

#ifndef org_jni_1zero_JniRawPtrImpl_JNI
#define org_jni_1zero_JniRawPtrImpl_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "JniRawPtrImpl_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
// There are no Java->Native methods.
#define DEFINE_JNI_FOR_JniRawPtrImpl()

// Class Accessors
#ifndef org_jni_1zero_JniRawPtrImpl_clazz_defined
#define org_jni_1zero_JniRawPtrImpl_clazz_defined
inline jclass org_jni_1zero_JniRawPtrImpl_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.jni_zero.JniRawPtrImpl";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


// Native to Java functions
static ::jni_zero::ScopedJavaLocalRef<jobject> Java_JniRawPtrImpl_Constructor(
    JNIEnv* env,
    int64_t nativePointer) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_jni_1zero_JniRawPtrImpl_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(J)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), nativePointer);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}


// jobject-subclass-aware definitions:
namespace jni_zero_internal {

template<>
class _CalledByNativesStatics<::org::jni_zero::JJniRawPtrImpl<jobject>> {
  public:
  template <typename T>
  static ::jni_zero::ScopedJavaLocalRef<::org::jni_zero::JJniRawPtrImpl<T>> New(
      JNIEnv* env,
      int64_t nativePointer) {
    return Java_JniRawPtrImpl_Constructor(env, nativePointer)
        .template As<::org::jni_zero::JJniRawPtrImpl<T>>();
  }

};


}  // namespace jni_zero_internal

namespace org::jni_zero {
using JniRawPtrImplJni = ::jni_zero_internal::_CalledByNativesStatics<::org::jni_zero::JJniRawPtrImpl<jobject>>;
}
#ifndef _JNI_ZERO_JniRawPtrImplJni_DEFINED
#define _JNI_ZERO_JniRawPtrImplJni_DEFINED
using ::org::jni_zero::JniRawPtrImplJni;
#endif


#pragma clang diagnostic pop
#endif  // org_jni_1zero_JniRawPtrImpl_JNI
