// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.jni_zero.JniRawPtrImpl

#ifndef org_jni_1zero_JniRawPtrImpl_SHARED_JNI
#define org_jni_1zero_JniRawPtrImpl_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_org_jni_zero_JJniRawPtrImpl_DEFINED
#define _JNI_ZERO_org_jni_zero_JJniRawPtrImpl_DEFINED
namespace org::jni_zero {
template <::jni_zero::internal::IsJobject T>
class _JJniRawPtrImpl : public _jobject {};
template <typename T>
using JJniRawPtrImpl = _JJniRawPtrImpl<T>*;
}
#endif

#ifndef _JNI_ZERO_JJniRawPtrImpl_DEFINED
#define _JNI_ZERO_JJniRawPtrImpl_DEFINED
using ::org::jni_zero::JJniRawPtrImpl;
#endif

#ifndef _JNI_ZERO_org_jni_zero_JJniTypeToken_DEFINED
#define _JNI_ZERO_org_jni_zero_JJniTypeToken_DEFINED
namespace org::jni_zero {
class _JJniTypeToken : public _jobject {};
using JJniTypeToken = _JJniTypeToken*;
}
#endif

#ifndef _JNI_ZERO_JJniTypeToken_DEFINED
#define _JNI_ZERO_JJniTypeToken_DEFINED
using ::org::jni_zero::JJniTypeToken;
#endif


#endif  // org_jni_1zero_JniRawPtrImpl_SHARED_JNI
