// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.jni_zero.JniZero

#ifndef org_jni_1zero_JniZero_SHARED_JNI
#define org_jni_1zero_JniZero_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_lang_JClassLoader_DEFINED
#define _JNI_ZERO_java_lang_JClassLoader_DEFINED
namespace java::lang {
class _JClassLoader : public _jobject {};
using JClassLoader = _JClassLoader*;
}
#endif

#ifndef _JNI_ZERO_JClassLoader_DEFINED
#define _JNI_ZERO_JClassLoader_DEFINED
using ::java::lang::JClassLoader;
#endif

#ifndef _JNI_ZERO_org_jni_zero_JJniPtrInner_DEFINED
#define _JNI_ZERO_org_jni_zero_JJniPtrInner_DEFINED
namespace org::jni_zero {
template <::jni_zero::internal::IsJobject T>
class _JJniPtrInner : public _jobject {};
template <typename T>
using JJniPtrInner = _JJniPtrInner<T>*;
}
#endif

#ifndef _JNI_ZERO_JJniPtrInner_DEFINED
#define _JNI_ZERO_JJniPtrInner_DEFINED
using ::org::jni_zero::JJniPtrInner;
#endif

#ifndef _JNI_ZERO_org_jni_zero_JJniZero_DEFINED
#define _JNI_ZERO_org_jni_zero_JJniZero_DEFINED
namespace org::jni_zero {
class _JJniZero : public _jobject {};
using JJniZero = _JJniZero*;
}
#endif

#ifndef _JNI_ZERO_JJniZero_DEFINED
#define _JNI_ZERO_JJniZero_DEFINED
using ::org::jni_zero::JJniZero;
#endif


#endif  // org_jni_1zero_JniZero_SHARED_JNI
