// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     org.jni_zero.JniZero

#ifndef org_jni_1zero_JniZero_JNI
#define org_jni_1zero_JniZero_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "JniZero_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Example signatures (to be implemented by #including file).
// * JNIEnv* parameters are optional.
// * Types do not have to be exact; they must accept rvalues of the examples.
//
// static void JNI_JniZero_SetJniClassLoader(
//     JNIEnv* env,
//     const jni_zero::JavaRef<::java::lang::JClassLoader>& classLoader);
//

// Triggers a compiler warning if DEFINE_JNI(JniZero) is forgotten (requires -Wunused-function).
static void YouForgotToCallMacro_DEFINE_JNI_JniZero() {}

// Java to native functions
#define DEFINE_JNI_FOR_JniZero()                                                                   \
  namespace {                                                                                      \
                                                                                                   \
  using namespace jni_zero;                                                                        \
  JNI_ZERO_BOUNDARY_EXPORT void Java_J_N_MMv8RAm7(                                                 \
      JNIEnv* env,                                                                                 \
      jclass jcaller,                                                                              \
      jobject classLoader) {                                                                       \
    /* Prevent -Wunused-function warning. */                                                       \
    YouForgotToCallMacro_DEFINE_JNI_JniZero();                                                     \
                                                                                                   \
    auto classLoader_ref = jni_zero::JavaRef<::java::lang::JClassLoader>::CreateLeaky(env,         \
        static_cast<::java::lang::JClassLoader>(classLoader));                                     \
    /* Lambda required to make "if constexpr" work properly. */                                    \
    auto dependent_context = [&](auto) {                                                           \
      /* Lambda required to disambiguate overloads. */                                             \
      auto func_wrapper = [&](auto&&... args) ->                                                   \
      decltype(JNI_JniZero_SetJniClassLoader(std::forward<decltype(args)>(args)...)) {             \
        return JNI_JniZero_SetJniClassLoader(std::forward<decltype(args)>(args)...);               \
      };                                                                                           \
      if constexpr (requires { func_wrapper(env, classLoader_ref); }) {                            \
        return func_wrapper(env, classLoader_ref);                                                 \
      } else if constexpr (requires { func_wrapper(classLoader_ref); }) {                          \
        return func_wrapper(classLoader_ref);                                                      \
      } else {                                                                                     \
        static_assert(false, "JNI_JniZero_SetJniClassLoader() is missing or has incorrect signature.\nIt should accept an optional JNIEnv* parameter as well as rvalues of the given types: (const jni_zero::JavaRef<JClassLoader>&)\nSee gen/jni_headers/third_party/jni_zero/generate_jni/JniZero_jni.h for an example."); \
      }                                                                                            \
    };                                                                                             \
    dependent_context(0);                                                                          \
  }                                                                                                \
                                                                                                   \
                                                                                                   \
  }  /* namespace */

// Class Accessors
#ifndef org_jni_1zero_JniZero_clazz_defined
#define org_jni_1zero_JniZero_clazz_defined
inline jclass org_jni_1zero_JniZero_clazz(JNIEnv* env) {
  static const char kClassName[] = "org.jni_zero.JniZero";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace jni_zero {

// Native to Java functions
static void Java_JniZero_crashIfMultiplexingMisaligned(
    JNIEnv* env,
    int64_t wholeHash,
    int64_t priorityHash) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_jni_1zero_JniZero_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "crashIfMultiplexingMisaligned",
      "(JJ)V",
      &cached_method_id);
  env->CallStaticVoidMethod(clazz, call_context.method_id(), wholeHash, priorityHash);
}

static int64_t Java_JniZero_getNativePtr(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& ptr) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_jni_1zero_JniZero_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getNativePtr",
      "(Lorg/jni_zero/JniPtrInner;)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), ptr.obj());
  return _ret;
}

static ::jni_zero::ScopedJavaLocalRef<jobjectArray> Java_JniZero_init(
    JNIEnv* env,
    bool rawPtrHooksEnabled) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_jni_1zero_JniZero_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "init",
      "(Z)[Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), rawPtrHooksEnabled);
  jobjectArray _ret2 = static_cast<jobjectArray>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jobjectArray>::Adopt(env, _ret2);
}



}  // namespace jni_zero

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::jni_zero;

template<>
class _CalledByNativesStatics<::org::jni_zero::JJniZero> {
  public:
  static void crashIfMultiplexingMisaligned(JNIEnv* env, int64_t wholeHash, int64_t priorityHash) {
    Java_JniZero_crashIfMultiplexingMisaligned(env, wholeHash, priorityHash);
  }

  static int64_t getNativePtr(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::org::jni_zero::JJniPtrInner<jobject>>& ptr) {
    return Java_JniZero_getNativePtr(env, ptr);
  }

  static ::jni_zero::ScopedJavaLocalRef<JArray<jobject>> init(
      JNIEnv* env,
      bool rawPtrHooksEnabled) {
    return Java_JniZero_init(env, rawPtrHooksEnabled)
        .As<JArray<jobject>>();
  }

};


}  // namespace jni_zero_internal

namespace org::jni_zero {
using JniZeroJni = ::jni_zero_internal::_CalledByNativesStatics<::org::jni_zero::JJniZero>;
}
#ifndef _JNI_ZERO_JniZeroJni_DEFINED
#define _JNI_ZERO_JniZeroJni_DEFINED
using ::org::jni_zero::JniZeroJni;
#endif


#pragma clang diagnostic pop
#endif  // org_jni_1zero_JniZero_JNI
