//
// This file was generated by //third_party/jni_zero/jni_zero.py
//
package org.jni_zero;

import javax.annotation.processing.Generated;
import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniTestInstanceHolder;
import org.jni_zero.internal.NullUnmarked;
import org.jni_zero.internal.Nullable;

@CheckDiscard("crbug.com/993421")
@Generated("JNI Zero")
@SuppressWarnings({"rawtypes", "unchecked"})
@NullUnmarked
class CommonApisJni implements CommonApis.Natives {
  private static @Nullable JniTestInstanceHolder sOverride;

  public static CommonApis.Natives get() {
    JniTestInstanceHolder holder = sOverride;
    if (holder != null && holder.value != null) {
      return (CommonApis.Natives) holder.value;
    }
    return new CommonApisJni();
  }

  public static void setInstanceForTesting(CommonApis.Natives impl) {
    if (sOverride == null) {
      sOverride = JniTestInstanceHolder.create();
    }
    sOverride.value = impl;
  }


  @Override
  public void deleteDeleterBasePtr(long ptr, long deleterAddress) {
    GEN_JNI.org_jni_1zero_CommonApis_deleteDeleterBasePtr(ptr, deleterAddress);
  }

  @Override
  public void releaseRawPtr(long ptr) {
    GEN_JNI.org_jni_1zero_CommonApis_releaseRawPtr(ptr);
  }
}
