// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.util.Arrays

#ifndef java_util_Arrays_SHARED_JNI
#define java_util_Arrays_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_lang_JComparable_DEFINED
#define _JNI_ZERO_java_lang_JComparable_DEFINED
namespace java::lang {
template <::jni_zero::internal::IsJobject T>
class _JComparable : public _jobject {};
template <typename T>
using JComparable = _JComparable<T>*;
}
#endif

#ifndef _JNI_ZERO_JComparable_DEFINED
#define _JNI_ZERO_JComparable_DEFINED
using ::java::lang::JComparable;
#endif

#ifndef _JNI_ZERO_java_util_JArrays_DEFINED
#define _JNI_ZERO_java_util_JArrays_DEFINED
namespace java::util {
class _JArrays : public _jobject {};
using JArrays = _JArrays*;
}
#endif

#ifndef _JNI_ZERO_JArrays_DEFINED
#define _JNI_ZERO_JArrays_DEFINED
using ::java::util::JArrays;
#endif

#ifndef _JNI_ZERO_java_util_JComparator_DEFINED
#define _JNI_ZERO_java_util_JComparator_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T>
class _JComparator : public _jobject {};
template <typename T>
using JComparator = _JComparator<T>*;
}
#endif

#ifndef _JNI_ZERO_JComparator_DEFINED
#define _JNI_ZERO_JComparator_DEFINED
using ::java::util::JComparator;
#endif

#ifndef _JNI_ZERO_java_util_JList_DEFINED
#define _JNI_ZERO_java_util_JList_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T>
class _JList : public _jobject {};
template <typename T>
using JList = _JList<T>*;
}
#endif

#ifndef _JNI_ZERO_JList_DEFINED
#define _JNI_ZERO_JList_DEFINED
using ::java::util::JList;
#endif

#ifndef _JNI_ZERO_java_util_JSpliterator_DEFINED
#define _JNI_ZERO_java_util_JSpliterator_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T>
class _JSpliterator : public _jobject {};
template <typename T>
using JSpliterator = _JSpliterator<T>*;
}
#endif

#ifndef _JNI_ZERO_JSpliterator_DEFINED
#define _JNI_ZERO_JSpliterator_DEFINED
using ::java::util::JSpliterator;
#endif

#ifndef _JNI_ZERO_java_util_JSpliterator_OfDouble_DEFINED
#define _JNI_ZERO_java_util_JSpliterator_OfDouble_DEFINED
namespace java::util {
class _JSpliterator_OfDouble : public _jobject {};
using JSpliterator_OfDouble = _JSpliterator_OfDouble*;
}
#endif

#ifndef _JNI_ZERO_JSpliterator_OfDouble_DEFINED
#define _JNI_ZERO_JSpliterator_OfDouble_DEFINED
using ::java::util::JSpliterator_OfDouble;
#endif

#ifndef _JNI_ZERO_java_util_JSpliterator_OfInt_DEFINED
#define _JNI_ZERO_java_util_JSpliterator_OfInt_DEFINED
namespace java::util {
class _JSpliterator_OfInt : public _jobject {};
using JSpliterator_OfInt = _JSpliterator_OfInt*;
}
#endif

#ifndef _JNI_ZERO_JSpliterator_OfInt_DEFINED
#define _JNI_ZERO_JSpliterator_OfInt_DEFINED
using ::java::util::JSpliterator_OfInt;
#endif

#ifndef _JNI_ZERO_java_util_JSpliterator_OfLong_DEFINED
#define _JNI_ZERO_java_util_JSpliterator_OfLong_DEFINED
namespace java::util {
class _JSpliterator_OfLong : public _jobject {};
using JSpliterator_OfLong = _JSpliterator_OfLong*;
}
#endif

#ifndef _JNI_ZERO_JSpliterator_OfLong_DEFINED
#define _JNI_ZERO_JSpliterator_OfLong_DEFINED
using ::java::util::JSpliterator_OfLong;
#endif

#ifndef _JNI_ZERO_java_util_function_JBinaryOperator_DEFINED
#define _JNI_ZERO_java_util_function_JBinaryOperator_DEFINED
namespace java::util::function {
template <::jni_zero::internal::IsJobject T>
class _JBinaryOperator : public _jobject {};
template <typename T>
using JBinaryOperator = _JBinaryOperator<T>*;
}
#endif

#ifndef _JNI_ZERO_JBinaryOperator_DEFINED
#define _JNI_ZERO_JBinaryOperator_DEFINED
using ::java::util::function::JBinaryOperator;
#endif

#ifndef _JNI_ZERO_java_util_function_JDoubleBinaryOperator_DEFINED
#define _JNI_ZERO_java_util_function_JDoubleBinaryOperator_DEFINED
namespace java::util::function {
class _JDoubleBinaryOperator : public _jobject {};
using JDoubleBinaryOperator = _JDoubleBinaryOperator*;
}
#endif

#ifndef _JNI_ZERO_JDoubleBinaryOperator_DEFINED
#define _JNI_ZERO_JDoubleBinaryOperator_DEFINED
using ::java::util::function::JDoubleBinaryOperator;
#endif

#ifndef _JNI_ZERO_java_util_function_JIntBinaryOperator_DEFINED
#define _JNI_ZERO_java_util_function_JIntBinaryOperator_DEFINED
namespace java::util::function {
class _JIntBinaryOperator : public _jobject {};
using JIntBinaryOperator = _JIntBinaryOperator*;
}
#endif

#ifndef _JNI_ZERO_JIntBinaryOperator_DEFINED
#define _JNI_ZERO_JIntBinaryOperator_DEFINED
using ::java::util::function::JIntBinaryOperator;
#endif

#ifndef _JNI_ZERO_java_util_function_JIntFunction_DEFINED
#define _JNI_ZERO_java_util_function_JIntFunction_DEFINED
namespace java::util::function {
template <::jni_zero::internal::IsJobject T>
class _JIntFunction : public _jobject {};
template <typename T>
using JIntFunction = _JIntFunction<T>*;
}
#endif

#ifndef _JNI_ZERO_JIntFunction_DEFINED
#define _JNI_ZERO_JIntFunction_DEFINED
using ::java::util::function::JIntFunction;
#endif

#ifndef _JNI_ZERO_java_util_function_JIntToDoubleFunction_DEFINED
#define _JNI_ZERO_java_util_function_JIntToDoubleFunction_DEFINED
namespace java::util::function {
class _JIntToDoubleFunction : public _jobject {};
using JIntToDoubleFunction = _JIntToDoubleFunction*;
}
#endif

#ifndef _JNI_ZERO_JIntToDoubleFunction_DEFINED
#define _JNI_ZERO_JIntToDoubleFunction_DEFINED
using ::java::util::function::JIntToDoubleFunction;
#endif

#ifndef _JNI_ZERO_java_util_function_JIntToLongFunction_DEFINED
#define _JNI_ZERO_java_util_function_JIntToLongFunction_DEFINED
namespace java::util::function {
class _JIntToLongFunction : public _jobject {};
using JIntToLongFunction = _JIntToLongFunction*;
}
#endif

#ifndef _JNI_ZERO_JIntToLongFunction_DEFINED
#define _JNI_ZERO_JIntToLongFunction_DEFINED
using ::java::util::function::JIntToLongFunction;
#endif

#ifndef _JNI_ZERO_java_util_function_JIntUnaryOperator_DEFINED
#define _JNI_ZERO_java_util_function_JIntUnaryOperator_DEFINED
namespace java::util::function {
class _JIntUnaryOperator : public _jobject {};
using JIntUnaryOperator = _JIntUnaryOperator*;
}
#endif

#ifndef _JNI_ZERO_JIntUnaryOperator_DEFINED
#define _JNI_ZERO_JIntUnaryOperator_DEFINED
using ::java::util::function::JIntUnaryOperator;
#endif

#ifndef _JNI_ZERO_java_util_function_JLongBinaryOperator_DEFINED
#define _JNI_ZERO_java_util_function_JLongBinaryOperator_DEFINED
namespace java::util::function {
class _JLongBinaryOperator : public _jobject {};
using JLongBinaryOperator = _JLongBinaryOperator*;
}
#endif

#ifndef _JNI_ZERO_JLongBinaryOperator_DEFINED
#define _JNI_ZERO_JLongBinaryOperator_DEFINED
using ::java::util::function::JLongBinaryOperator;
#endif

#ifndef _JNI_ZERO_java_util_stream_JDoubleStream_DEFINED
#define _JNI_ZERO_java_util_stream_JDoubleStream_DEFINED
namespace java::util::stream {
class _JDoubleStream : public _jobject {};
using JDoubleStream = _JDoubleStream*;
}
#endif

#ifndef _JNI_ZERO_JDoubleStream_DEFINED
#define _JNI_ZERO_JDoubleStream_DEFINED
using ::java::util::stream::JDoubleStream;
#endif

#ifndef _JNI_ZERO_java_util_stream_JIntStream_DEFINED
#define _JNI_ZERO_java_util_stream_JIntStream_DEFINED
namespace java::util::stream {
class _JIntStream : public _jobject {};
using JIntStream = _JIntStream*;
}
#endif

#ifndef _JNI_ZERO_JIntStream_DEFINED
#define _JNI_ZERO_JIntStream_DEFINED
using ::java::util::stream::JIntStream;
#endif

#ifndef _JNI_ZERO_java_util_stream_JLongStream_DEFINED
#define _JNI_ZERO_java_util_stream_JLongStream_DEFINED
namespace java::util::stream {
class _JLongStream : public _jobject {};
using JLongStream = _JLongStream*;
}
#endif

#ifndef _JNI_ZERO_JLongStream_DEFINED
#define _JNI_ZERO_JLongStream_DEFINED
using ::java::util::stream::JLongStream;
#endif

#ifndef _JNI_ZERO_java_util_stream_JStream_DEFINED
#define _JNI_ZERO_java_util_stream_JStream_DEFINED
namespace java::util::stream {
template <::jni_zero::internal::IsJobject T>
class _JStream : public _jobject {};
template <typename T>
using JStream = _JStream<T>*;
}
#endif

#ifndef _JNI_ZERO_JStream_DEFINED
#define _JNI_ZERO_JStream_DEFINED
using ::java::util::stream::JStream;
#endif


#endif  // java_util_Arrays_SHARED_JNI
