// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.Boolean

#ifndef java_lang_Boolean_JNI
#define java_lang_Boolean_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "Boolean_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Class Accessors
#ifndef java_lang_Boolean_clazz_defined
#define java_lang_Boolean_clazz_defined
inline jclass java_lang_Boolean_clazz(JNIEnv* env) {
  static const char kClassName[] = "java.lang.Boolean";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


// FieldId Accessors
inline jfieldID java_lang_Boolean_fieldId_FALSE(JNIEnv* env) {
  static std::atomic<jfieldID> cached_field_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  JNI_ZERO_DCHECK(clazz);
  ::jni_zero::internal::InitializeFieldID<::jni_zero::internal::FieldID::TYPE_STATIC>(env, clazz, "FALSE", "Ljava/lang/Boolean;", &cached_field_id);
  return cached_field_id.load(std::memory_order_relaxed);
}

inline jfieldID java_lang_Boolean_fieldId_TRUE(JNIEnv* env) {
  static std::atomic<jfieldID> cached_field_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  JNI_ZERO_DCHECK(clazz);
  ::jni_zero::internal::InitializeFieldID<::jni_zero::internal::FieldID::TYPE_STATIC>(env, clazz, "TRUE", "Ljava/lang/Boolean;", &cached_field_id);
  return cached_field_id.load(std::memory_order_relaxed);
}

inline jfieldID java_lang_Boolean_fieldId_TYPE(JNIEnv* env) {
  static std::atomic<jfieldID> cached_field_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  JNI_ZERO_DCHECK(clazz);
  ::jni_zero::internal::InitializeFieldID<::jni_zero::internal::FieldID::TYPE_STATIC>(env, clazz, "TYPE", "Ljava/lang/Class;", &cached_field_id);
  return cached_field_id.load(std::memory_order_relaxed);
}


namespace JNI_Boolean {

// Native to Java functions
[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Boolean_Constructor__boolean(
    JNIEnv* env,
    bool p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Z)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Boolean_Constructor__String(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/lang/String;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static bool Java_Boolean_booleanValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "booleanValue",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Boolean_compareTo__Boolean(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Boolean;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Boolean_compareTo__Object(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Object;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static bool Java_Boolean_equals(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "equals",
      "(Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Boolean_hashCode(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "hashCode",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Boolean_toString(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "toString",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static int32_t Java_Boolean_compare(JNIEnv* env, bool p0, bool p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "compare",
      "(ZZ)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static bool Java_Boolean_getBoolean(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getBoolean",
      "(Ljava/lang/String;)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Boolean_hashCode(JNIEnv* env, bool p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "hashCode",
      "(Z)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static bool Java_Boolean_logicalAnd(JNIEnv* env, bool p0, bool p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "logicalAnd",
      "(ZZ)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static bool Java_Boolean_logicalOr(JNIEnv* env, bool p0, bool p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "logicalOr",
      "(ZZ)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static bool Java_Boolean_logicalXor(JNIEnv* env, bool p0, bool p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "logicalXor",
      "(ZZ)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static bool Java_Boolean_parseBoolean(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseBoolean",
      "(Ljava/lang/String;)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Boolean_toString(
    JNIEnv* env,
    bool p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toString",
      "(Z)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Boolean_valueOf__boolean(
    JNIEnv* env,
    bool p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(Z)Ljava/lang/Boolean;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Boolean_valueOf__String(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(Ljava/lang/String;)Ljava/lang/Boolean;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace JNI_Boolean

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::JNI_Boolean;

template<>
class _CalledByNativesStatics<::java::lang::JBoolean> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JBoolean> Get_FALSE(JNIEnv* env) {
    jclass clazz = java_lang_Boolean_clazz(env);
    JNI_ZERO_DCHECK(clazz);
    jfieldID field_id = java_lang_Boolean_fieldId_FALSE(env);
    return ::jni_zero::ScopedJavaLocalRef<>::Adopt(env, env->GetStaticObjectField(clazz, field_id))
        .As<::java::lang::JBoolean>();
  }
  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JBoolean> Get_TRUE(JNIEnv* env) {
    jclass clazz = java_lang_Boolean_clazz(env);
    JNI_ZERO_DCHECK(clazz);
    jfieldID field_id = java_lang_Boolean_fieldId_TRUE(env);
    return ::jni_zero::ScopedJavaLocalRef<>::Adopt(env, env->GetStaticObjectField(clazz, field_id))
        .As<::java::lang::JBoolean>();
  }
  static ::jni_zero::ScopedJavaLocalRef<jclass> Get_TYPE(JNIEnv* env) {
    jclass clazz = java_lang_Boolean_clazz(env);
    JNI_ZERO_DCHECK(clazz);
    jfieldID field_id = java_lang_Boolean_fieldId_TYPE(env);
    return ::jni_zero::ScopedJavaLocalRef<>::Adopt(env, env->GetStaticObjectField(clazz, field_id))
        .As<jclass>();
  }
  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JBoolean> New(JNIEnv* env, bool p0) {
    return Java_Boolean_Constructor__boolean(env, p0)
        .As<::java::lang::JBoolean>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JBoolean> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Boolean_Constructor__String(env, p0)
        .As<::java::lang::JBoolean>();
  }

  static int32_t compare(JNIEnv* env, bool p0, bool p1) {
    return Java_Boolean_compare(env, p0, p1);
  }

  static bool getBoolean(JNIEnv* env, const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Boolean_getBoolean(env, p0);
  }

  static int32_t hashCode(JNIEnv* env, bool p0) {
    return Java_Boolean_hashCode(env, p0);
  }

  static bool logicalAnd(JNIEnv* env, bool p0, bool p1) {
    return Java_Boolean_logicalAnd(env, p0, p1);
  }

  static bool logicalOr(JNIEnv* env, bool p0, bool p1) {
    return Java_Boolean_logicalOr(env, p0, p1);
  }

  static bool logicalXor(JNIEnv* env, bool p0, bool p1) {
    return Java_Boolean_logicalXor(env, p0, p1);
  }

  static bool parseBoolean(JNIEnv* env, const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Boolean_parseBoolean(env, p0);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toString(JNIEnv* env, bool p0) {
    return Java_Boolean_toString(env, p0);
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JBoolean> valueOf(JNIEnv* env, bool p0) {
    return Java_Boolean_valueOf__boolean(env, p0)
        .As<::java::lang::JBoolean>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JBoolean> valueOf(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Boolean_valueOf__String(env, p0)
        .As<::java::lang::JBoolean>();
  }

};

template<>
class _CalledByNatives<::java::lang::JBoolean> {
  public:
  bool booleanValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JBoolean>*>(this);
    return Java_Boolean_booleanValue(env, *this_obj);
  }

  int32_t compareTo(JNIEnv* env, const ::jni_zero::JavaRef<::java::lang::JBoolean>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JBoolean>*>(this);
    return Java_Boolean_compareTo__Boolean(env, *this_obj, p0);
  }

  int32_t compareTo(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JBoolean>*>(this);
    return Java_Boolean_compareTo__Object(env, *this_obj, p0);
  }

  bool equals(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JBoolean>*>(this);
    return Java_Boolean_equals(env, *this_obj, p0);
  }

  int32_t hashCode(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JBoolean>*>(this);
    return Java_Boolean_hashCode(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<jstring> toString(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JBoolean>*>(this);
    return Java_Boolean_toString(env, *this_obj);
  }

};


}  // namespace jni_zero_internal

namespace java::lang {
using BooleanJni = ::jni_zero_internal::_CalledByNativesStatics<::java::lang::JBoolean>;
}
#ifndef _JNI_ZERO_BooleanJni_DEFINED
#define _JNI_ZERO_BooleanJni_DEFINED
using ::java::lang::BooleanJni;
#endif


#pragma clang diagnostic pop
#endif  // java_lang_Boolean_JNI
