// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.Boolean

#ifndef java_lang_Boolean_SHARED_JNI
#define java_lang_Boolean_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_lang_JBoolean_DEFINED
#define _JNI_ZERO_java_lang_JBoolean_DEFINED
namespace java::lang {
class _JBoolean : public _jobject {};
using JBoolean = _JBoolean*;
}
#endif

#ifndef _JNI_ZERO_JBoolean_DEFINED
#define _JNI_ZERO_JBoolean_DEFINED
using ::java::lang::JBoolean;
#endif


#endif  // java_lang_Boolean_SHARED_JNI
