// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.util.Collection

#ifndef java_util_Collection_SHARED_JNI
#define java_util_Collection_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_util_JCollection_DEFINED
#define _JNI_ZERO_java_util_JCollection_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T>
class _JCollection : public _jobject {};
template <typename T>
using JCollection = _JCollection<T>*;
}
#endif

#ifndef _JNI_ZERO_JCollection_DEFINED
#define _JNI_ZERO_JCollection_DEFINED
using ::java::util::JCollection;
#endif

#ifndef _JNI_ZERO_java_util_JIterator_DEFINED
#define _JNI_ZERO_java_util_JIterator_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T>
class _JIterator : public _jobject {};
template <typename T>
using JIterator = _JIterator<T>*;
}
#endif

#ifndef _JNI_ZERO_JIterator_DEFINED
#define _JNI_ZERO_JIterator_DEFINED
using ::java::util::JIterator;
#endif

#ifndef _JNI_ZERO_java_util_JSpliterator_DEFINED
#define _JNI_ZERO_java_util_JSpliterator_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T>
class _JSpliterator : public _jobject {};
template <typename T>
using JSpliterator = _JSpliterator<T>*;
}
#endif

#ifndef _JNI_ZERO_JSpliterator_DEFINED
#define _JNI_ZERO_JSpliterator_DEFINED
using ::java::util::JSpliterator;
#endif

#ifndef _JNI_ZERO_java_util_function_JIntFunction_DEFINED
#define _JNI_ZERO_java_util_function_JIntFunction_DEFINED
namespace java::util::function {
template <::jni_zero::internal::IsJobject T>
class _JIntFunction : public _jobject {};
template <typename T>
using JIntFunction = _JIntFunction<T>*;
}
#endif

#ifndef _JNI_ZERO_JIntFunction_DEFINED
#define _JNI_ZERO_JIntFunction_DEFINED
using ::java::util::function::JIntFunction;
#endif

#ifndef _JNI_ZERO_java_util_function_JPredicate_DEFINED
#define _JNI_ZERO_java_util_function_JPredicate_DEFINED
namespace java::util::function {
template <::jni_zero::internal::IsJobject T>
class _JPredicate : public _jobject {};
template <typename T>
using JPredicate = _JPredicate<T>*;
}
#endif

#ifndef _JNI_ZERO_JPredicate_DEFINED
#define _JNI_ZERO_JPredicate_DEFINED
using ::java::util::function::JPredicate;
#endif

#ifndef _JNI_ZERO_java_util_stream_JStream_DEFINED
#define _JNI_ZERO_java_util_stream_JStream_DEFINED
namespace java::util::stream {
template <::jni_zero::internal::IsJobject T>
class _JStream : public _jobject {};
template <typename T>
using JStream = _JStream<T>*;
}
#endif

#ifndef _JNI_ZERO_JStream_DEFINED
#define _JNI_ZERO_JStream_DEFINED
using ::java::util::stream::JStream;
#endif


#endif  // java_util_Collection_SHARED_JNI
