// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.Double

#ifndef java_lang_Double_SHARED_JNI
#define java_lang_Double_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_lang_JDouble_DEFINED
#define _JNI_ZERO_java_lang_JDouble_DEFINED
namespace java::lang {
class _JDouble : public _jobject {};
using JDouble = _JDouble*;
}
#endif

#ifndef _JNI_ZERO_JDouble_DEFINED
#define _JNI_ZERO_JDouble_DEFINED
using ::java::lang::JDouble;
#endif


#endif  // java_lang_Double_SHARED_JNI
