// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.Float

#ifndef java_lang_Float_JNI
#define java_lang_Float_JNI

#include <jni.h>
#include <limits>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "Float_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Class Accessors
#ifndef java_lang_Float_clazz_defined
#define java_lang_Float_clazz_defined
inline jclass java_lang_Float_clazz(JNIEnv* env) {
  static const char kClassName[] = "java.lang.Float";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


// FieldId Accessors
inline jfieldID java_lang_Float_fieldId_TYPE(JNIEnv* env) {
  static std::atomic<jfieldID> cached_field_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  JNI_ZERO_DCHECK(clazz);
  ::jni_zero::internal::InitializeFieldID<::jni_zero::internal::FieldID::TYPE_STATIC>(env, clazz, "TYPE", "Ljava/lang/Class;", &cached_field_id);
  return cached_field_id.load(std::memory_order_relaxed);
}


namespace JNI_Float {

// Native to Java functions
[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Float_Constructor__double(
    JNIEnv* env,
    double p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(D)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Float_Constructor__float(
    JNIEnv* env,
    float p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(F)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Float_Constructor__String(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/lang/String;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static int8_t Java_Float_byteValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "byteValue",
      "()B",
      &cached_method_id);
  auto _ret = env->CallByteMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Float_compareTo__Float(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Float;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Float_compareTo__Object(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Object;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static double Java_Float_doubleValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "doubleValue",
      "()D",
      &cached_method_id);
  auto _ret = env->CallDoubleMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static bool Java_Float_equals(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "equals",
      "(Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static float Java_Float_floatValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "floatValue",
      "()F",
      &cached_method_id);
  auto _ret = env->CallFloatMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Float_hashCode(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "hashCode",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Float_intValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "intValue",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static bool Java_Float_isInfinite(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "isInfinite",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static bool Java_Float_isNaN(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "isNaN",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int64_t Java_Float_longValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "longValue",
      "()J",
      &cached_method_id);
  auto _ret = env->CallLongMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int16_t Java_Float_shortValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "shortValue",
      "()S",
      &cached_method_id);
  auto _ret = env->CallShortMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Float_toString(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "toString",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static int32_t Java_Float_compare(JNIEnv* env, float p0, float p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "compare",
      "(FF)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static float Java_Float_float16ToFloat(JNIEnv* env, int16_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "float16ToFloat",
      "(S)F",
      &cached_method_id);
  auto _ret = env->CallStaticFloatMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static int16_t Java_Float_floatToFloat16(JNIEnv* env, float p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "floatToFloat16",
      "(F)S",
      &cached_method_id);
  auto _ret = env->CallStaticShortMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static int32_t Java_Float_floatToIntBits(JNIEnv* env, float p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "floatToIntBits",
      "(F)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static int32_t Java_Float_floatToRawIntBits(JNIEnv* env, float p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "floatToRawIntBits",
      "(F)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static int32_t Java_Float_hashCode(JNIEnv* env, float p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "hashCode",
      "(F)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static float Java_Float_intBitsToFloat(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "intBitsToFloat",
      "(I)F",
      &cached_method_id);
  auto _ret = env->CallStaticFloatMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static bool Java_Float_isFinite(JNIEnv* env, float p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "isFinite",
      "(F)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static bool Java_Float_isInfinite(JNIEnv* env, float p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "isInfinite",
      "(F)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static bool Java_Float_isNaN(JNIEnv* env, float p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "isNaN",
      "(F)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static float Java_Float_max(JNIEnv* env, float p0, float p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "max",
      "(FF)F",
      &cached_method_id);
  auto _ret = env->CallStaticFloatMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static float Java_Float_min(JNIEnv* env, float p0, float p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "min",
      "(FF)F",
      &cached_method_id);
  auto _ret = env->CallStaticFloatMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static float Java_Float_parseFloat(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseFloat",
      "(Ljava/lang/String;)F",
      &cached_method_id);
  auto _ret = env->CallStaticFloatMethod(clazz, call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static float Java_Float_sum(JNIEnv* env, float p0, float p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "sum",
      "(FF)F",
      &cached_method_id);
  auto _ret = env->CallStaticFloatMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Float_toHexString(
    JNIEnv* env,
    float p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toHexString",
      "(F)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Float_toString(
    JNIEnv* env,
    float p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toString",
      "(F)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Float_valueOf__float(
    JNIEnv* env,
    float p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(F)Ljava/lang/Float;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Float_valueOf__String(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Float_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(Ljava/lang/String;)Ljava/lang/Float;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace JNI_Float

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::JNI_Float;

template<>
class _CalledByNativesStatics<::java::lang::JFloat> {
  public:
  static inline constexpr int32_t BYTES = 4;
  static inline constexpr int32_t MAX_EXPONENT = 127;
  static inline constexpr float MAX_VALUE = 3.4028235E38f;
  static inline constexpr int32_t MIN_EXPONENT = -126;
  static inline constexpr float MIN_NORMAL = 1.1754944E-38f;
  static inline constexpr float MIN_VALUE = 1.4E-45f;
  static inline constexpr float NEGATIVE_INFINITY = -std::numeric_limits<float>::infinity();
  static inline constexpr float NaN = std::numeric_limits<float>::quiet_NaN();
  static inline constexpr float POSITIVE_INFINITY = std::numeric_limits<float>::infinity();
  static inline constexpr int32_t PRECISION = 24;
  static inline constexpr int32_t SIZE = 32;
  static int32_t Get_BYTES(JNIEnv* env) {
    return 4;
  }
  static int32_t Get_MAX_EXPONENT(JNIEnv* env) {
    return 127;
  }
  static float Get_MAX_VALUE(JNIEnv* env) {
    return 3.4028235E38f;
  }
  static int32_t Get_MIN_EXPONENT(JNIEnv* env) {
    return -126;
  }
  static float Get_MIN_NORMAL(JNIEnv* env) {
    return 1.1754944E-38f;
  }
  static float Get_MIN_VALUE(JNIEnv* env) {
    return 1.4E-45f;
  }
  static float Get_NEGATIVE_INFINITY(JNIEnv* env) {
    return -std::numeric_limits<float>::infinity();
  }
  static float Get_NaN(JNIEnv* env) {
    return std::numeric_limits<float>::quiet_NaN();
  }
  static float Get_POSITIVE_INFINITY(JNIEnv* env) {
    return std::numeric_limits<float>::infinity();
  }
  static int32_t Get_PRECISION(JNIEnv* env) {
    return 24;
  }
  static int32_t Get_SIZE(JNIEnv* env) {
    return 32;
  }
  static ::jni_zero::ScopedJavaLocalRef<jclass> Get_TYPE(JNIEnv* env) {
    jclass clazz = java_lang_Float_clazz(env);
    JNI_ZERO_DCHECK(clazz);
    jfieldID field_id = java_lang_Float_fieldId_TYPE(env);
    return ::jni_zero::ScopedJavaLocalRef<>::Adopt(env, env->GetStaticObjectField(clazz, field_id))
        .As<jclass>();
  }
  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JFloat> New(JNIEnv* env, double p0) {
    return Java_Float_Constructor__double(env, p0)
        .As<::java::lang::JFloat>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JFloat> New(JNIEnv* env, float p0) {
    return Java_Float_Constructor__float(env, p0)
        .As<::java::lang::JFloat>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JFloat> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Float_Constructor__String(env, p0)
        .As<::java::lang::JFloat>();
  }

  static int32_t compare(JNIEnv* env, float p0, float p1) {
    return Java_Float_compare(env, p0, p1);
  }

  static float float16ToFloat(JNIEnv* env, int16_t p0) {
    return Java_Float_float16ToFloat(env, p0);
  }

  static int16_t floatToFloat16(JNIEnv* env, float p0) {
    return Java_Float_floatToFloat16(env, p0);
  }

  static int32_t floatToIntBits(JNIEnv* env, float p0) {
    return Java_Float_floatToIntBits(env, p0);
  }

  static int32_t floatToRawIntBits(JNIEnv* env, float p0) {
    return Java_Float_floatToRawIntBits(env, p0);
  }

  static int32_t hashCode(JNIEnv* env, float p0) {
    return Java_Float_hashCode(env, p0);
  }

  static float intBitsToFloat(JNIEnv* env, JniIntWrapper p0) {
    return Java_Float_intBitsToFloat(env, p0);
  }

  static bool isFinite(JNIEnv* env, float p0) {
    return Java_Float_isFinite(env, p0);
  }

  static bool isInfinite(JNIEnv* env, float p0) {
    return Java_Float_isInfinite(env, p0);
  }

  static bool isNaN(JNIEnv* env, float p0) {
    return Java_Float_isNaN(env, p0);
  }

  static float max(JNIEnv* env, float p0, float p1) {
    return Java_Float_max(env, p0, p1);
  }

  static float min(JNIEnv* env, float p0, float p1) {
    return Java_Float_min(env, p0, p1);
  }

  static float parseFloat(JNIEnv* env, const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Float_parseFloat(env, p0);
  }

  static float sum(JNIEnv* env, float p0, float p1) {
    return Java_Float_sum(env, p0, p1);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toHexString(JNIEnv* env, float p0) {
    return Java_Float_toHexString(env, p0);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toString(JNIEnv* env, float p0) {
    return Java_Float_toString(env, p0);
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JFloat> valueOf(JNIEnv* env, float p0) {
    return Java_Float_valueOf__float(env, p0)
        .As<::java::lang::JFloat>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JFloat> valueOf(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Float_valueOf__String(env, p0)
        .As<::java::lang::JFloat>();
  }

};

template<>
class _CalledByNatives<::java::lang::JFloat> {
  public:
  int8_t byteValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JFloat>*>(this);
    return Java_Float_byteValue(env, *this_obj);
  }

  int32_t compareTo(JNIEnv* env, const ::jni_zero::JavaRef<::java::lang::JFloat>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JFloat>*>(this);
    return Java_Float_compareTo__Float(env, *this_obj, p0);
  }

  int32_t compareTo(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JFloat>*>(this);
    return Java_Float_compareTo__Object(env, *this_obj, p0);
  }

  double doubleValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JFloat>*>(this);
    return Java_Float_doubleValue(env, *this_obj);
  }

  bool equals(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JFloat>*>(this);
    return Java_Float_equals(env, *this_obj, p0);
  }

  float floatValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JFloat>*>(this);
    return Java_Float_floatValue(env, *this_obj);
  }

  int32_t hashCode(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JFloat>*>(this);
    return Java_Float_hashCode(env, *this_obj);
  }

  int32_t intValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JFloat>*>(this);
    return Java_Float_intValue(env, *this_obj);
  }

  bool isInfinite(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JFloat>*>(this);
    return Java_Float_isInfinite(env, *this_obj);
  }

  bool isNaN(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JFloat>*>(this);
    return Java_Float_isNaN(env, *this_obj);
  }

  int64_t longValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JFloat>*>(this);
    return Java_Float_longValue(env, *this_obj);
  }

  int16_t shortValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JFloat>*>(this);
    return Java_Float_shortValue(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<jstring> toString(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JFloat>*>(this);
    return Java_Float_toString(env, *this_obj);
  }

};


}  // namespace jni_zero_internal

namespace java::lang {
using FloatJni = ::jni_zero_internal::_CalledByNativesStatics<::java::lang::JFloat>;
}
#ifndef _JNI_ZERO_FloatJni_DEFINED
#define _JNI_ZERO_FloatJni_DEFINED
using ::java::lang::FloatJni;
#endif


#pragma clang diagnostic pop
#endif  // java_lang_Float_JNI
