// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.Float

#ifndef java_lang_Float_SHARED_JNI
#define java_lang_Float_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_lang_JFloat_DEFINED
#define _JNI_ZERO_java_lang_JFloat_DEFINED
namespace java::lang {
class _JFloat : public _jobject {};
using JFloat = _JFloat*;
}
#endif

#ifndef _JNI_ZERO_JFloat_DEFINED
#define _JNI_ZERO_JFloat_DEFINED
using ::java::lang::JFloat;
#endif


#endif  // java_lang_Float_SHARED_JNI
