// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.Integer

#ifndef java_lang_Integer_JNI
#define java_lang_Integer_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "Integer_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Class Accessors
#ifndef java_lang_Integer_clazz_defined
#define java_lang_Integer_clazz_defined
inline jclass java_lang_Integer_clazz(JNIEnv* env) {
  static const char kClassName[] = "java.lang.Integer";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


// FieldId Accessors
inline jfieldID java_lang_Integer_fieldId_TYPE(JNIEnv* env) {
  static std::atomic<jfieldID> cached_field_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  JNI_ZERO_DCHECK(clazz);
  ::jni_zero::internal::InitializeFieldID<::jni_zero::internal::FieldID::TYPE_STATIC>(env, clazz, "TYPE", "Ljava/lang/Class;", &cached_field_id);
  return cached_field_id.load(std::memory_order_relaxed);
}


namespace JNI_Integer {

// Native to Java functions
[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_Constructor__int(
    JNIEnv* env,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(I)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), as_jint(p0));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_Constructor__String(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/lang/String;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static int8_t Java_Integer_byteValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "byteValue",
      "()B",
      &cached_method_id);
  auto _ret = env->CallByteMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_compareTo__Integer(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Integer;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_compareTo__Object(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Object;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static double Java_Integer_doubleValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "doubleValue",
      "()D",
      &cached_method_id);
  auto _ret = env->CallDoubleMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static bool Java_Integer_equals(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "equals",
      "(Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static float Java_Integer_floatValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "floatValue",
      "()F",
      &cached_method_id);
  auto _ret = env->CallFloatMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_hashCode(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "hashCode",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_intValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "intValue",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int64_t Java_Integer_longValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "longValue",
      "()J",
      &cached_method_id);
  auto _ret = env->CallLongMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int16_t Java_Integer_shortValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "shortValue",
      "()S",
      &cached_method_id);
  auto _ret = env->CallShortMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Integer_toString(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "toString",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static int32_t Java_Integer_bitCount(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "bitCount",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_compare(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "compare",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_compareUnsigned(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "compareUnsigned",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_compress(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "compress",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_decode(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "decode",
      "(Ljava/lang/String;)Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static int32_t Java_Integer_divideUnsigned(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "divideUnsigned",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_expand(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "expand",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_getInteger(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getInteger",
      "(Ljava/lang/String;)Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_getInteger__String__int(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getInteger",
      "(Ljava/lang/String;I)Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj(), as_jint(p1));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_getInteger__String__Integer(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0,
    const ::jni_zero::JavaRef<jobject>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getInteger",
      "(Ljava/lang/String;Ljava/lang/Integer;)Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj(), p1.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static int32_t Java_Integer_hashCode(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "hashCode",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_highestOneBit(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "highestOneBit",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_lowestOneBit(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "lowestOneBit",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_max(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "max",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_min(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "min",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_numberOfLeadingZeros(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "numberOfLeadingZeros",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_numberOfTrailingZeros(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "numberOfTrailingZeros",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_parseInt(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0,
    JniIntWrapper p1,
    JniIntWrapper p2,
    JniIntWrapper p3) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseInt",
      "(Ljava/lang/CharSequence;III)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      as_jint(p1),
      as_jint(p2),
      as_jint(p3));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_parseInt(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseInt",
      "(Ljava/lang/String;)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_parseInt(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseInt",
      "(Ljava/lang/String;I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0.obj(), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_parseUnsignedInt(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0,
    JniIntWrapper p1,
    JniIntWrapper p2,
    JniIntWrapper p3) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseUnsignedInt",
      "(Ljava/lang/CharSequence;III)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      as_jint(p1),
      as_jint(p2),
      as_jint(p3));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_parseUnsignedInt(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseUnsignedInt",
      "(Ljava/lang/String;)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_parseUnsignedInt(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseUnsignedInt",
      "(Ljava/lang/String;I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0.obj(), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_remainderUnsigned(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "remainderUnsigned",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_reverse(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "reverse",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_reverseBytes(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "reverseBytes",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_rotateLeft(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "rotateLeft",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_rotateRight(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "rotateRight",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_signum(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "signum",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Integer_sum(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "sum",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Integer_toBinaryString(
    JNIEnv* env,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toBinaryString",
      "(I)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(p0));
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Integer_toHexString(
    JNIEnv* env,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toHexString",
      "(I)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(p0));
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Integer_toOctalString(
    JNIEnv* env,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toOctalString",
      "(I)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(p0));
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Integer_toString(
    JNIEnv* env,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toString",
      "(I)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(p0));
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Integer_toString(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toString",
      "(II)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(
      clazz,
      call_context.method_id(),
      as_jint(p0),
      as_jint(p1));
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static int64_t Java_Integer_toUnsignedLong(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toUnsignedLong",
      "(I)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Integer_toUnsignedString(
    JNIEnv* env,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toUnsignedString",
      "(I)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(p0));
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Integer_toUnsignedString(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toUnsignedString",
      "(II)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(
      clazz,
      call_context.method_id(),
      as_jint(p0),
      as_jint(p1));
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_valueOf__int(
    JNIEnv* env,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(I)Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(p0));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_valueOf__String(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(Ljava/lang/String;)Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_valueOf(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(Ljava/lang/String;I)Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj(), as_jint(p1));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace JNI_Integer

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::JNI_Integer;

template<>
class _CalledByNativesStatics<::java::lang::JInteger> {
  public:
  static inline constexpr int32_t BYTES = 4;
  static inline constexpr int32_t MAX_VALUE = 2147483647;
  static inline constexpr int32_t MIN_VALUE = -2147483648;
  static inline constexpr int32_t SIZE = 32;
  static int32_t Get_BYTES(JNIEnv* env) {
    return 4;
  }
  static int32_t Get_MAX_VALUE(JNIEnv* env) {
    return 2147483647;
  }
  static int32_t Get_MIN_VALUE(JNIEnv* env) {
    return -2147483648;
  }
  static int32_t Get_SIZE(JNIEnv* env) {
    return 32;
  }
  static ::jni_zero::ScopedJavaLocalRef<jclass> Get_TYPE(JNIEnv* env) {
    jclass clazz = java_lang_Integer_clazz(env);
    JNI_ZERO_DCHECK(clazz);
    jfieldID field_id = java_lang_Integer_fieldId_TYPE(env);
    return ::jni_zero::ScopedJavaLocalRef<>::Adopt(env, env->GetStaticObjectField(clazz, field_id))
        .As<jclass>();
  }
  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JInteger> New(JNIEnv* env, JniIntWrapper p0) {
    return Java_Integer_Constructor__int(env, p0)
        .As<::java::lang::JInteger>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JInteger> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Integer_Constructor__String(env, p0)
        .As<::java::lang::JInteger>();
  }

  static int32_t bitCount(JNIEnv* env, JniIntWrapper p0) {
    return Java_Integer_bitCount(env, p0);
  }

  static int32_t compare(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
    return Java_Integer_compare(env, p0, p1);
  }

  static int32_t compareUnsigned(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
    return Java_Integer_compareUnsigned(env, p0, p1);
  }

  static int32_t compress(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
    return Java_Integer_compress(env, p0, p1);
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JInteger> decode(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Integer_decode(env, p0)
        .As<::java::lang::JInteger>();
  }

  static int32_t divideUnsigned(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
    return Java_Integer_divideUnsigned(env, p0, p1);
  }

  static int32_t expand(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
    return Java_Integer_expand(env, p0, p1);
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JInteger> getInteger(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Integer_getInteger(env, p0)
        .As<::java::lang::JInteger>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JInteger> getInteger(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0,
      JniIntWrapper p1) {
    return Java_Integer_getInteger__String__int(env, p0, p1)
        .As<::java::lang::JInteger>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JInteger> getInteger(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0,
      const ::jni_zero::JavaRef<::java::lang::JInteger>& p1) {
    return Java_Integer_getInteger__String__Integer(env, p0, p1)
        .As<::java::lang::JInteger>();
  }

  static int32_t hashCode(JNIEnv* env, JniIntWrapper p0) {
    return Java_Integer_hashCode(env, p0);
  }

  static int32_t highestOneBit(JNIEnv* env, JniIntWrapper p0) {
    return Java_Integer_highestOneBit(env, p0);
  }

  static int32_t lowestOneBit(JNIEnv* env, JniIntWrapper p0) {
    return Java_Integer_lowestOneBit(env, p0);
  }

  static int32_t max(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
    return Java_Integer_max(env, p0, p1);
  }

  static int32_t min(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
    return Java_Integer_min(env, p0, p1);
  }

  static int32_t numberOfLeadingZeros(JNIEnv* env, JniIntWrapper p0) {
    return Java_Integer_numberOfLeadingZeros(env, p0);
  }

  static int32_t numberOfTrailingZeros(JNIEnv* env, JniIntWrapper p0) {
    return Java_Integer_numberOfTrailingZeros(env, p0);
  }

  static int32_t parseInt(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::lang::JCharSequence>& p0,
      JniIntWrapper p1,
      JniIntWrapper p2,
      JniIntWrapper p3) {
    return Java_Integer_parseInt(env, p0, p1, p2, p3);
  }

  static int32_t parseInt(JNIEnv* env, const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Integer_parseInt(env, p0);
  }

  static int32_t parseInt(JNIEnv* env, const ::jni_zero::JavaRef<jstring>& p0, JniIntWrapper p1) {
    return Java_Integer_parseInt(env, p0, p1);
  }

  static int32_t parseUnsignedInt(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::lang::JCharSequence>& p0,
      JniIntWrapper p1,
      JniIntWrapper p2,
      JniIntWrapper p3) {
    return Java_Integer_parseUnsignedInt(env, p0, p1, p2, p3);
  }

  static int32_t parseUnsignedInt(JNIEnv* env, const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Integer_parseUnsignedInt(env, p0);
  }

  static int32_t parseUnsignedInt(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0,
      JniIntWrapper p1) {
    return Java_Integer_parseUnsignedInt(env, p0, p1);
  }

  static int32_t remainderUnsigned(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
    return Java_Integer_remainderUnsigned(env, p0, p1);
  }

  static int32_t reverse(JNIEnv* env, JniIntWrapper p0) {
    return Java_Integer_reverse(env, p0);
  }

  static int32_t reverseBytes(JNIEnv* env, JniIntWrapper p0) {
    return Java_Integer_reverseBytes(env, p0);
  }

  static int32_t rotateLeft(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
    return Java_Integer_rotateLeft(env, p0, p1);
  }

  static int32_t rotateRight(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
    return Java_Integer_rotateRight(env, p0, p1);
  }

  static int32_t signum(JNIEnv* env, JniIntWrapper p0) {
    return Java_Integer_signum(env, p0);
  }

  static int32_t sum(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
    return Java_Integer_sum(env, p0, p1);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toBinaryString(JNIEnv* env, JniIntWrapper p0) {
    return Java_Integer_toBinaryString(env, p0);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toHexString(JNIEnv* env, JniIntWrapper p0) {
    return Java_Integer_toHexString(env, p0);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toOctalString(JNIEnv* env, JniIntWrapper p0) {
    return Java_Integer_toOctalString(env, p0);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toString(JNIEnv* env, JniIntWrapper p0) {
    return Java_Integer_toString(env, p0);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toString(
      JNIEnv* env,
      JniIntWrapper p0,
      JniIntWrapper p1) {
    return Java_Integer_toString(env, p0, p1);
  }

  static int64_t toUnsignedLong(JNIEnv* env, JniIntWrapper p0) {
    return Java_Integer_toUnsignedLong(env, p0);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toUnsignedString(JNIEnv* env, JniIntWrapper p0) {
    return Java_Integer_toUnsignedString(env, p0);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toUnsignedString(
      JNIEnv* env,
      JniIntWrapper p0,
      JniIntWrapper p1) {
    return Java_Integer_toUnsignedString(env, p0, p1);
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JInteger> valueOf(
      JNIEnv* env,
      JniIntWrapper p0) {
    return Java_Integer_valueOf__int(env, p0)
        .As<::java::lang::JInteger>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JInteger> valueOf(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Integer_valueOf__String(env, p0)
        .As<::java::lang::JInteger>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JInteger> valueOf(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0,
      JniIntWrapper p1) {
    return Java_Integer_valueOf(env, p0, p1)
        .As<::java::lang::JInteger>();
  }

};

template<>
class _CalledByNatives<::java::lang::JInteger> {
  public:
  int8_t byteValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JInteger>*>(this);
    return Java_Integer_byteValue(env, *this_obj);
  }

  int32_t compareTo(JNIEnv* env, const ::jni_zero::JavaRef<::java::lang::JInteger>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JInteger>*>(this);
    return Java_Integer_compareTo__Integer(env, *this_obj, p0);
  }

  int32_t compareTo(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JInteger>*>(this);
    return Java_Integer_compareTo__Object(env, *this_obj, p0);
  }

  double doubleValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JInteger>*>(this);
    return Java_Integer_doubleValue(env, *this_obj);
  }

  bool equals(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JInteger>*>(this);
    return Java_Integer_equals(env, *this_obj, p0);
  }

  float floatValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JInteger>*>(this);
    return Java_Integer_floatValue(env, *this_obj);
  }

  int32_t hashCode(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JInteger>*>(this);
    return Java_Integer_hashCode(env, *this_obj);
  }

  int32_t intValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JInteger>*>(this);
    return Java_Integer_intValue(env, *this_obj);
  }

  int64_t longValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JInteger>*>(this);
    return Java_Integer_longValue(env, *this_obj);
  }

  int16_t shortValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JInteger>*>(this);
    return Java_Integer_shortValue(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<jstring> toString(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JInteger>*>(this);
    return Java_Integer_toString(env, *this_obj);
  }

};


}  // namespace jni_zero_internal

namespace java::lang {
using IntegerJni = ::jni_zero_internal::_CalledByNativesStatics<::java::lang::JInteger>;
}
#ifndef _JNI_ZERO_IntegerJni_DEFINED
#define _JNI_ZERO_IntegerJni_DEFINED
using ::java::lang::IntegerJni;
#endif


#pragma clang diagnostic pop
#endif  // java_lang_Integer_JNI
