// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.Long

#ifndef java_lang_Long_SHARED_JNI
#define java_lang_Long_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_lang_JCharSequence_DEFINED
#define _JNI_ZERO_java_lang_JCharSequence_DEFINED
namespace java::lang {
class _JCharSequence : public _jobject {};
using JCharSequence = _JCharSequence*;
}
#endif

#ifndef _JNI_ZERO_JCharSequence_DEFINED
#define _JNI_ZERO_JCharSequence_DEFINED
using ::java::lang::JCharSequence;
#endif

#ifndef _JNI_ZERO_java_lang_JLong_DEFINED
#define _JNI_ZERO_java_lang_JLong_DEFINED
namespace java::lang {
class _JLong : public _jobject {};
using JLong = _JLong*;
}
#endif

#ifndef _JNI_ZERO_JLong_DEFINED
#define _JNI_ZERO_JLong_DEFINED
using ::java::lang::JLong;
#endif


#endif  // java_lang_Long_SHARED_JNI
