// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.Long

#ifndef java_lang_Long_JNI
#define java_lang_Long_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "Long_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Class Accessors
#ifndef java_lang_Long_clazz_defined
#define java_lang_Long_clazz_defined
inline jclass java_lang_Long_clazz(JNIEnv* env) {
  static const char kClassName[] = "java.lang.Long";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


// FieldId Accessors
inline jfieldID java_lang_Long_fieldId_TYPE(JNIEnv* env) {
  static std::atomic<jfieldID> cached_field_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  JNI_ZERO_DCHECK(clazz);
  ::jni_zero::internal::InitializeFieldID<::jni_zero::internal::FieldID::TYPE_STATIC>(env, clazz, "TYPE", "Ljava/lang/Class;", &cached_field_id);
  return cached_field_id.load(std::memory_order_relaxed);
}


namespace JNI_Long {

// Native to Java functions
[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Long_Constructor__long(
    JNIEnv* env,
    int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(J)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Long_Constructor__String(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/lang/String;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static int8_t Java_Long_byteValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "byteValue",
      "()B",
      &cached_method_id);
  auto _ret = env->CallByteMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Long_compareTo__Long(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Long;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Long_compareTo__Object(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Object;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static double Java_Long_doubleValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "doubleValue",
      "()D",
      &cached_method_id);
  auto _ret = env->CallDoubleMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static bool Java_Long_equals(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "equals",
      "(Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static float Java_Long_floatValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "floatValue",
      "()F",
      &cached_method_id);
  auto _ret = env->CallFloatMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Long_hashCode(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "hashCode",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Long_intValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "intValue",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_longValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "longValue",
      "()J",
      &cached_method_id);
  auto _ret = env->CallLongMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int16_t Java_Long_shortValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "shortValue",
      "()S",
      &cached_method_id);
  auto _ret = env->CallShortMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Long_toString(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "toString",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static int32_t Java_Long_bitCount(JNIEnv* env, int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "bitCount",
      "(J)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static int32_t Java_Long_compare(JNIEnv* env, int64_t p0, int64_t p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "compare",
      "(JJ)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static int32_t Java_Long_compareUnsigned(JNIEnv* env, int64_t p0, int64_t p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "compareUnsigned",
      "(JJ)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_compress(JNIEnv* env, int64_t p0, int64_t p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "compress",
      "(JJ)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Long_decode(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "decode",
      "(Ljava/lang/String;)Ljava/lang/Long;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static int64_t Java_Long_divideUnsigned(JNIEnv* env, int64_t p0, int64_t p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "divideUnsigned",
      "(JJ)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_expand(JNIEnv* env, int64_t p0, int64_t p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "expand",
      "(JJ)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Long_getLong(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getLong",
      "(Ljava/lang/String;)Ljava/lang/Long;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Long_getLong__String__long(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0,
    int64_t p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getLong",
      "(Ljava/lang/String;J)Ljava/lang/Long;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj(), p1);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Long_getLong__String__Long(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0,
    const ::jni_zero::JavaRef<jobject>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getLong",
      "(Ljava/lang/String;Ljava/lang/Long;)Ljava/lang/Long;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj(), p1.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static int32_t Java_Long_hashCode(JNIEnv* env, int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "hashCode",
      "(J)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_highestOneBit(JNIEnv* env, int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "highestOneBit",
      "(J)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_lowestOneBit(JNIEnv* env, int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "lowestOneBit",
      "(J)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_max(JNIEnv* env, int64_t p0, int64_t p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "max",
      "(JJ)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_min(JNIEnv* env, int64_t p0, int64_t p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "min",
      "(JJ)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static int32_t Java_Long_numberOfLeadingZeros(JNIEnv* env, int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "numberOfLeadingZeros",
      "(J)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static int32_t Java_Long_numberOfTrailingZeros(JNIEnv* env, int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "numberOfTrailingZeros",
      "(J)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_parseLong(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0,
    JniIntWrapper p1,
    JniIntWrapper p2,
    JniIntWrapper p3) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseLong",
      "(Ljava/lang/CharSequence;III)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      as_jint(p1),
      as_jint(p2),
      as_jint(p3));
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_parseLong(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseLong",
      "(Ljava/lang/String;)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_parseLong(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseLong",
      "(Ljava/lang/String;I)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0.obj(), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_parseUnsignedLong(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0,
    JniIntWrapper p1,
    JniIntWrapper p2,
    JniIntWrapper p3) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseUnsignedLong",
      "(Ljava/lang/CharSequence;III)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      as_jint(p1),
      as_jint(p2),
      as_jint(p3));
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_parseUnsignedLong(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseUnsignedLong",
      "(Ljava/lang/String;)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_parseUnsignedLong(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseUnsignedLong",
      "(Ljava/lang/String;I)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0.obj(), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_remainderUnsigned(JNIEnv* env, int64_t p0, int64_t p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "remainderUnsigned",
      "(JJ)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_reverse(JNIEnv* env, int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "reverse",
      "(J)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_reverseBytes(JNIEnv* env, int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "reverseBytes",
      "(J)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_rotateLeft(JNIEnv* env, int64_t p0, JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "rotateLeft",
      "(JI)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0, as_jint(p1));
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_rotateRight(JNIEnv* env, int64_t p0, JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "rotateRight",
      "(JI)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0, as_jint(p1));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Long_signum(JNIEnv* env, int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "signum",
      "(J)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static int64_t Java_Long_sum(JNIEnv* env, int64_t p0, int64_t p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "sum",
      "(JJ)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Long_toBinaryString(
    JNIEnv* env,
    int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toBinaryString",
      "(J)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Long_toHexString(
    JNIEnv* env,
    int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toHexString",
      "(J)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Long_toOctalString(
    JNIEnv* env,
    int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toOctalString",
      "(J)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Long_toString(
    JNIEnv* env,
    int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toString",
      "(J)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Long_toString(
    JNIEnv* env,
    int64_t p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toString",
      "(JI)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0, as_jint(p1));
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Long_toUnsignedString(
    JNIEnv* env,
    int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toUnsignedString",
      "(J)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Long_toUnsignedString(
    JNIEnv* env,
    int64_t p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toUnsignedString",
      "(JI)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0, as_jint(p1));
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Long_valueOf__long(
    JNIEnv* env,
    int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(J)Ljava/lang/Long;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Long_valueOf__String(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(Ljava/lang/String;)Ljava/lang/Long;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Long_valueOf(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(Ljava/lang/String;I)Ljava/lang/Long;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj(), as_jint(p1));
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace JNI_Long

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::JNI_Long;

template<>
class _CalledByNativesStatics<::java::lang::JLong> {
  public:
  static inline constexpr int32_t BYTES = 8;
  static inline constexpr int64_t MAX_VALUE = 9223372036854775807LL;
  static inline constexpr int64_t MIN_VALUE = -9223372036854775807LL - 1LL;
  static inline constexpr int32_t SIZE = 64;
  static int32_t Get_BYTES(JNIEnv* env) {
    return 8;
  }
  static int64_t Get_MAX_VALUE(JNIEnv* env) {
    return 9223372036854775807LL;
  }
  static int64_t Get_MIN_VALUE(JNIEnv* env) {
    return -9223372036854775807LL - 1LL;
  }
  static int32_t Get_SIZE(JNIEnv* env) {
    return 64;
  }
  static ::jni_zero::ScopedJavaLocalRef<jclass> Get_TYPE(JNIEnv* env) {
    jclass clazz = java_lang_Long_clazz(env);
    JNI_ZERO_DCHECK(clazz);
    jfieldID field_id = java_lang_Long_fieldId_TYPE(env);
    return ::jni_zero::ScopedJavaLocalRef<>::Adopt(env, env->GetStaticObjectField(clazz, field_id))
        .As<jclass>();
  }
  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JLong> New(JNIEnv* env, int64_t p0) {
    return Java_Long_Constructor__long(env, p0)
        .As<::java::lang::JLong>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JLong> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Long_Constructor__String(env, p0)
        .As<::java::lang::JLong>();
  }

  static int32_t bitCount(JNIEnv* env, int64_t p0) {
    return Java_Long_bitCount(env, p0);
  }

  static int32_t compare(JNIEnv* env, int64_t p0, int64_t p1) {
    return Java_Long_compare(env, p0, p1);
  }

  static int32_t compareUnsigned(JNIEnv* env, int64_t p0, int64_t p1) {
    return Java_Long_compareUnsigned(env, p0, p1);
  }

  static int64_t compress(JNIEnv* env, int64_t p0, int64_t p1) {
    return Java_Long_compress(env, p0, p1);
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JLong> decode(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Long_decode(env, p0)
        .As<::java::lang::JLong>();
  }

  static int64_t divideUnsigned(JNIEnv* env, int64_t p0, int64_t p1) {
    return Java_Long_divideUnsigned(env, p0, p1);
  }

  static int64_t expand(JNIEnv* env, int64_t p0, int64_t p1) {
    return Java_Long_expand(env, p0, p1);
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JLong> getLong(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Long_getLong(env, p0)
        .As<::java::lang::JLong>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JLong> getLong(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0,
      int64_t p1) {
    return Java_Long_getLong__String__long(env, p0, p1)
        .As<::java::lang::JLong>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JLong> getLong(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0,
      const ::jni_zero::JavaRef<::java::lang::JLong>& p1) {
    return Java_Long_getLong__String__Long(env, p0, p1)
        .As<::java::lang::JLong>();
  }

  static int32_t hashCode(JNIEnv* env, int64_t p0) {
    return Java_Long_hashCode(env, p0);
  }

  static int64_t highestOneBit(JNIEnv* env, int64_t p0) {
    return Java_Long_highestOneBit(env, p0);
  }

  static int64_t lowestOneBit(JNIEnv* env, int64_t p0) {
    return Java_Long_lowestOneBit(env, p0);
  }

  static int64_t max(JNIEnv* env, int64_t p0, int64_t p1) {
    return Java_Long_max(env, p0, p1);
  }

  static int64_t min(JNIEnv* env, int64_t p0, int64_t p1) {
    return Java_Long_min(env, p0, p1);
  }

  static int32_t numberOfLeadingZeros(JNIEnv* env, int64_t p0) {
    return Java_Long_numberOfLeadingZeros(env, p0);
  }

  static int32_t numberOfTrailingZeros(JNIEnv* env, int64_t p0) {
    return Java_Long_numberOfTrailingZeros(env, p0);
  }

  static int64_t parseLong(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::lang::JCharSequence>& p0,
      JniIntWrapper p1,
      JniIntWrapper p2,
      JniIntWrapper p3) {
    return Java_Long_parseLong(env, p0, p1, p2, p3);
  }

  static int64_t parseLong(JNIEnv* env, const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Long_parseLong(env, p0);
  }

  static int64_t parseLong(JNIEnv* env, const ::jni_zero::JavaRef<jstring>& p0, JniIntWrapper p1) {
    return Java_Long_parseLong(env, p0, p1);
  }

  static int64_t parseUnsignedLong(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::lang::JCharSequence>& p0,
      JniIntWrapper p1,
      JniIntWrapper p2,
      JniIntWrapper p3) {
    return Java_Long_parseUnsignedLong(env, p0, p1, p2, p3);
  }

  static int64_t parseUnsignedLong(JNIEnv* env, const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Long_parseUnsignedLong(env, p0);
  }

  static int64_t parseUnsignedLong(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0,
      JniIntWrapper p1) {
    return Java_Long_parseUnsignedLong(env, p0, p1);
  }

  static int64_t remainderUnsigned(JNIEnv* env, int64_t p0, int64_t p1) {
    return Java_Long_remainderUnsigned(env, p0, p1);
  }

  static int64_t reverse(JNIEnv* env, int64_t p0) {
    return Java_Long_reverse(env, p0);
  }

  static int64_t reverseBytes(JNIEnv* env, int64_t p0) {
    return Java_Long_reverseBytes(env, p0);
  }

  static int64_t rotateLeft(JNIEnv* env, int64_t p0, JniIntWrapper p1) {
    return Java_Long_rotateLeft(env, p0, p1);
  }

  static int64_t rotateRight(JNIEnv* env, int64_t p0, JniIntWrapper p1) {
    return Java_Long_rotateRight(env, p0, p1);
  }

  static int32_t signum(JNIEnv* env, int64_t p0) {
    return Java_Long_signum(env, p0);
  }

  static int64_t sum(JNIEnv* env, int64_t p0, int64_t p1) {
    return Java_Long_sum(env, p0, p1);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toBinaryString(JNIEnv* env, int64_t p0) {
    return Java_Long_toBinaryString(env, p0);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toHexString(JNIEnv* env, int64_t p0) {
    return Java_Long_toHexString(env, p0);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toOctalString(JNIEnv* env, int64_t p0) {
    return Java_Long_toOctalString(env, p0);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toString(JNIEnv* env, int64_t p0) {
    return Java_Long_toString(env, p0);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toString(
      JNIEnv* env,
      int64_t p0,
      JniIntWrapper p1) {
    return Java_Long_toString(env, p0, p1);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toUnsignedString(JNIEnv* env, int64_t p0) {
    return Java_Long_toUnsignedString(env, p0);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> toUnsignedString(
      JNIEnv* env,
      int64_t p0,
      JniIntWrapper p1) {
    return Java_Long_toUnsignedString(env, p0, p1);
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JLong> valueOf(JNIEnv* env, int64_t p0) {
    return Java_Long_valueOf__long(env, p0)
        .As<::java::lang::JLong>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JLong> valueOf(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Long_valueOf__String(env, p0)
        .As<::java::lang::JLong>();
  }

  static ::jni_zero::ScopedJavaLocalRef<::java::lang::JLong> valueOf(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0,
      JniIntWrapper p1) {
    return Java_Long_valueOf(env, p0, p1)
        .As<::java::lang::JLong>();
  }

};

template<>
class _CalledByNatives<::java::lang::JLong> {
  public:
  int8_t byteValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JLong>*>(this);
    return Java_Long_byteValue(env, *this_obj);
  }

  int32_t compareTo(JNIEnv* env, const ::jni_zero::JavaRef<::java::lang::JLong>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JLong>*>(this);
    return Java_Long_compareTo__Long(env, *this_obj, p0);
  }

  int32_t compareTo(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JLong>*>(this);
    return Java_Long_compareTo__Object(env, *this_obj, p0);
  }

  double doubleValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JLong>*>(this);
    return Java_Long_doubleValue(env, *this_obj);
  }

  bool equals(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JLong>*>(this);
    return Java_Long_equals(env, *this_obj, p0);
  }

  float floatValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JLong>*>(this);
    return Java_Long_floatValue(env, *this_obj);
  }

  int32_t hashCode(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JLong>*>(this);
    return Java_Long_hashCode(env, *this_obj);
  }

  int32_t intValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JLong>*>(this);
    return Java_Long_intValue(env, *this_obj);
  }

  int64_t longValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JLong>*>(this);
    return Java_Long_longValue(env, *this_obj);
  }

  int16_t shortValue(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JLong>*>(this);
    return Java_Long_shortValue(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<jstring> toString(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::lang::JLong>*>(this);
    return Java_Long_toString(env, *this_obj);
  }

};


}  // namespace jni_zero_internal

namespace java::lang {
using LongJni = ::jni_zero_internal::_CalledByNativesStatics<::java::lang::JLong>;
}
#ifndef _JNI_ZERO_LongJni_DEFINED
#define _JNI_ZERO_LongJni_DEFINED
using ::java::lang::LongJni;
#endif


#pragma clang diagnostic pop
#endif  // java_lang_Long_JNI
