// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.util.Map

#ifndef java_util_Map_SHARED_JNI
#define java_util_Map_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_util_JCollection_DEFINED
#define _JNI_ZERO_java_util_JCollection_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T>
class _JCollection : public _jobject {};
template <typename T>
using JCollection = _JCollection<T>*;
}
#endif

#ifndef _JNI_ZERO_JCollection_DEFINED
#define _JNI_ZERO_JCollection_DEFINED
using ::java::util::JCollection;
#endif

#ifndef _JNI_ZERO_java_util_JMap_DEFINED
#define _JNI_ZERO_java_util_JMap_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T1, ::jni_zero::internal::IsJobject T2>
class _JMap : public _jobject {};
template <typename T1, typename T2>
using JMap = _JMap<T1, T2>*;
}
#endif

#ifndef _JNI_ZERO_JMap_DEFINED
#define _JNI_ZERO_JMap_DEFINED
using ::java::util::JMap;
#endif

#ifndef _JNI_ZERO_java_util_JMap_Entry_DEFINED
#define _JNI_ZERO_java_util_JMap_Entry_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T1, ::jni_zero::internal::IsJobject T2>
class _JMap_Entry : public _jobject {};
template <typename T1, typename T2>
using JMap_Entry = _JMap_Entry<T1, T2>*;
}
#endif

#ifndef _JNI_ZERO_JMap_Entry_DEFINED
#define _JNI_ZERO_JMap_Entry_DEFINED
using ::java::util::JMap_Entry;
#endif

#ifndef _JNI_ZERO_java_util_JSet_DEFINED
#define _JNI_ZERO_java_util_JSet_DEFINED
namespace java::util {
template <::jni_zero::internal::IsJobject T>
class _JSet : public _jobject {};
template <typename T>
using JSet = _JSet<T>*;
}
#endif

#ifndef _JNI_ZERO_JSet_DEFINED
#define _JNI_ZERO_JSet_DEFINED
using ::java::util::JSet;
#endif

#ifndef _JNI_ZERO_java_util_function_JBiConsumer_DEFINED
#define _JNI_ZERO_java_util_function_JBiConsumer_DEFINED
namespace java::util::function {
template <::jni_zero::internal::IsJobject T1, ::jni_zero::internal::IsJobject T2>
class _JBiConsumer : public _jobject {};
template <typename T1, typename T2>
using JBiConsumer = _JBiConsumer<T1, T2>*;
}
#endif

#ifndef _JNI_ZERO_JBiConsumer_DEFINED
#define _JNI_ZERO_JBiConsumer_DEFINED
using ::java::util::function::JBiConsumer;
#endif

#ifndef _JNI_ZERO_java_util_function_JBiFunction_DEFINED
#define _JNI_ZERO_java_util_function_JBiFunction_DEFINED
namespace java::util::function {
template <::jni_zero::internal::IsJobject T1, ::jni_zero::internal::IsJobject T2, ::jni_zero::internal::IsJobject T3>
class _JBiFunction : public _jobject {};
template <typename T1, typename T2, typename T3>
using JBiFunction = _JBiFunction<T1, T2, T3>*;
}
#endif

#ifndef _JNI_ZERO_JBiFunction_DEFINED
#define _JNI_ZERO_JBiFunction_DEFINED
using ::java::util::function::JBiFunction;
#endif

#ifndef _JNI_ZERO_java_util_function_JFunction_DEFINED
#define _JNI_ZERO_java_util_function_JFunction_DEFINED
namespace java::util::function {
template <::jni_zero::internal::IsJobject T1, ::jni_zero::internal::IsJobject T2>
class _JFunction : public _jobject {};
template <typename T1, typename T2>
using JFunction = _JFunction<T1, T2>*;
}
#endif

#ifndef _JNI_ZERO_JFunction_DEFINED
#define _JNI_ZERO_JFunction_DEFINED
using ::java::util::function::JFunction;
#endif


#endif  // java_util_Map_SHARED_JNI
