// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.util.Map

#ifndef java_util_Map_JNI
#define java_util_Map_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "Map_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Class Accessors
#ifndef java_util_Map_clazz_defined
#define java_util_Map_clazz_defined
inline jclass java_util_Map_clazz(JNIEnv* env) {
  static const char kClassName[] = "java.util.Map";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

#ifndef java_util_Map_00024Entry_clazz_defined
#define java_util_Map_00024Entry_clazz_defined
inline jclass java_util_Map_00024Entry_clazz(JNIEnv* env) {
  static const char kClassName[] = "java.util.Map$Entry";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace JNI_Map {

// Native to Java functions
[[maybe_unused]] static void Java_Map_clear(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "clear",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_compute(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compute",
      "(Ljava/lang/Object;Ljava/util/function/BiFunction;)Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj(), p1.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_computeIfAbsent(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "computeIfAbsent",
      "(Ljava/lang/Object;Ljava/util/function/Function;)Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj(), p1.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_computeIfPresent(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "computeIfPresent",
      "(Ljava/lang/Object;Ljava/util/function/BiFunction;)Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj(), p1.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static bool Java_Map_containsKey(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "containsKey",
      "(Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static bool Java_Map_containsValue(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "containsValue",
      "(Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_entrySet(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "entrySet",
      "()Ljava/util/Set;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static bool Java_Map_equals(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "equals",
      "(Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static void Java_Map_forEach(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "forEach",
      "(Ljava/util/function/BiConsumer;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0.obj());
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_get(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "get",
      "(Ljava/lang/Object;)Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_getOrDefault(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getOrDefault",
      "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj(), p1.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static int32_t Java_Map_hashCode(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "hashCode",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static bool Java_Map_isEmpty(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "isEmpty",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_keySet(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "keySet",
      "()Ljava/util/Set;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_merge(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1,
    const ::jni_zero::JavaRef<jobject>& p2) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "merge",
      "(Ljava/lang/Object;Ljava/lang/Object;Ljava/util/function/BiFunction;)Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(
      obj.obj(),
      call_context.method_id(),
      p0.obj(),
      p1.obj(),
      p2.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_put(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "put",
      "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj(), p1.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static void Java_Map_putAll(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "putAll",
      "(Ljava/util/Map;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0.obj());
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_putIfAbsent(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "putIfAbsent",
      "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj(), p1.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static bool Java_Map_remove(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "remove",
      "(Ljava/lang/Object;Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj(), p1.obj());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_remove(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "remove",
      "(Ljava/lang/Object;)Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static bool Java_Map_replace(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1,
    const ::jni_zero::JavaRef<jobject>& p2) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "replace",
      "(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(
      obj.obj(),
      call_context.method_id(),
      p0.obj(),
      p1.obj(),
      p2.obj());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_replace(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "replace",
      "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj(), p1.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static void Java_Map_replaceAll(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "replaceAll",
      "(Ljava/util/function/BiFunction;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0.obj());
}

[[maybe_unused]] static int32_t Java_Map_size(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "size",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_values(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "values",
      "()Ljava/util/Collection;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_copyOf(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "copyOf",
      "(Ljava/util/Map;)Ljava/util/Map;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_entry(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "entry",
      "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/Map$Entry;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj(), p1.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_of(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "of",
      "()Ljava/util/Map;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_of(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "of",
      "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/Map;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj(), p1.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_of(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1,
    const ::jni_zero::JavaRef<jobject>& p2,
    const ::jni_zero::JavaRef<jobject>& p3) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "of",
      "(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/Map;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      p1.obj(),
      p2.obj(),
      p3.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_of(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1,
    const ::jni_zero::JavaRef<jobject>& p2,
    const ::jni_zero::JavaRef<jobject>& p3,
    const ::jni_zero::JavaRef<jobject>& p4,
    const ::jni_zero::JavaRef<jobject>& p5) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "of",
      "(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/Map;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      p1.obj(),
      p2.obj(),
      p3.obj(),
      p4.obj(),
      p5.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_of(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1,
    const ::jni_zero::JavaRef<jobject>& p2,
    const ::jni_zero::JavaRef<jobject>& p3,
    const ::jni_zero::JavaRef<jobject>& p4,
    const ::jni_zero::JavaRef<jobject>& p5,
    const ::jni_zero::JavaRef<jobject>& p6,
    const ::jni_zero::JavaRef<jobject>& p7) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "of",
      "(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/Map;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      p1.obj(),
      p2.obj(),
      p3.obj(),
      p4.obj(),
      p5.obj(),
      p6.obj(),
      p7.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_of(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1,
    const ::jni_zero::JavaRef<jobject>& p2,
    const ::jni_zero::JavaRef<jobject>& p3,
    const ::jni_zero::JavaRef<jobject>& p4,
    const ::jni_zero::JavaRef<jobject>& p5,
    const ::jni_zero::JavaRef<jobject>& p6,
    const ::jni_zero::JavaRef<jobject>& p7,
    const ::jni_zero::JavaRef<jobject>& p8,
    const ::jni_zero::JavaRef<jobject>& p9) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "of",
      "(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/Map;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      p1.obj(),
      p2.obj(),
      p3.obj(),
      p4.obj(),
      p5.obj(),
      p6.obj(),
      p7.obj(),
      p8.obj(),
      p9.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_of(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1,
    const ::jni_zero::JavaRef<jobject>& p2,
    const ::jni_zero::JavaRef<jobject>& p3,
    const ::jni_zero::JavaRef<jobject>& p4,
    const ::jni_zero::JavaRef<jobject>& p5,
    const ::jni_zero::JavaRef<jobject>& p6,
    const ::jni_zero::JavaRef<jobject>& p7,
    const ::jni_zero::JavaRef<jobject>& p8,
    const ::jni_zero::JavaRef<jobject>& p9,
    const ::jni_zero::JavaRef<jobject>& p10,
    const ::jni_zero::JavaRef<jobject>& p11) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "of",
      "(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/Map;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      p1.obj(),
      p2.obj(),
      p3.obj(),
      p4.obj(),
      p5.obj(),
      p6.obj(),
      p7.obj(),
      p8.obj(),
      p9.obj(),
      p10.obj(),
      p11.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_of(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1,
    const ::jni_zero::JavaRef<jobject>& p2,
    const ::jni_zero::JavaRef<jobject>& p3,
    const ::jni_zero::JavaRef<jobject>& p4,
    const ::jni_zero::JavaRef<jobject>& p5,
    const ::jni_zero::JavaRef<jobject>& p6,
    const ::jni_zero::JavaRef<jobject>& p7,
    const ::jni_zero::JavaRef<jobject>& p8,
    const ::jni_zero::JavaRef<jobject>& p9,
    const ::jni_zero::JavaRef<jobject>& p10,
    const ::jni_zero::JavaRef<jobject>& p11,
    const ::jni_zero::JavaRef<jobject>& p12,
    const ::jni_zero::JavaRef<jobject>& p13) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "of",
      "(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/Map;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      p1.obj(),
      p2.obj(),
      p3.obj(),
      p4.obj(),
      p5.obj(),
      p6.obj(),
      p7.obj(),
      p8.obj(),
      p9.obj(),
      p10.obj(),
      p11.obj(),
      p12.obj(),
      p13.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_of(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1,
    const ::jni_zero::JavaRef<jobject>& p2,
    const ::jni_zero::JavaRef<jobject>& p3,
    const ::jni_zero::JavaRef<jobject>& p4,
    const ::jni_zero::JavaRef<jobject>& p5,
    const ::jni_zero::JavaRef<jobject>& p6,
    const ::jni_zero::JavaRef<jobject>& p7,
    const ::jni_zero::JavaRef<jobject>& p8,
    const ::jni_zero::JavaRef<jobject>& p9,
    const ::jni_zero::JavaRef<jobject>& p10,
    const ::jni_zero::JavaRef<jobject>& p11,
    const ::jni_zero::JavaRef<jobject>& p12,
    const ::jni_zero::JavaRef<jobject>& p13,
    const ::jni_zero::JavaRef<jobject>& p14,
    const ::jni_zero::JavaRef<jobject>& p15) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "of",
      "(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/Map;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      p1.obj(),
      p2.obj(),
      p3.obj(),
      p4.obj(),
      p5.obj(),
      p6.obj(),
      p7.obj(),
      p8.obj(),
      p9.obj(),
      p10.obj(),
      p11.obj(),
      p12.obj(),
      p13.obj(),
      p14.obj(),
      p15.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_of(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1,
    const ::jni_zero::JavaRef<jobject>& p2,
    const ::jni_zero::JavaRef<jobject>& p3,
    const ::jni_zero::JavaRef<jobject>& p4,
    const ::jni_zero::JavaRef<jobject>& p5,
    const ::jni_zero::JavaRef<jobject>& p6,
    const ::jni_zero::JavaRef<jobject>& p7,
    const ::jni_zero::JavaRef<jobject>& p8,
    const ::jni_zero::JavaRef<jobject>& p9,
    const ::jni_zero::JavaRef<jobject>& p10,
    const ::jni_zero::JavaRef<jobject>& p11,
    const ::jni_zero::JavaRef<jobject>& p12,
    const ::jni_zero::JavaRef<jobject>& p13,
    const ::jni_zero::JavaRef<jobject>& p14,
    const ::jni_zero::JavaRef<jobject>& p15,
    const ::jni_zero::JavaRef<jobject>& p16,
    const ::jni_zero::JavaRef<jobject>& p17) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "of",
      "(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/Map;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      p1.obj(),
      p2.obj(),
      p3.obj(),
      p4.obj(),
      p5.obj(),
      p6.obj(),
      p7.obj(),
      p8.obj(),
      p9.obj(),
      p10.obj(),
      p11.obj(),
      p12.obj(),
      p13.obj(),
      p14.obj(),
      p15.obj(),
      p16.obj(),
      p17.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_of(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& p0,
    const ::jni_zero::JavaRef<jobject>& p1,
    const ::jni_zero::JavaRef<jobject>& p2,
    const ::jni_zero::JavaRef<jobject>& p3,
    const ::jni_zero::JavaRef<jobject>& p4,
    const ::jni_zero::JavaRef<jobject>& p5,
    const ::jni_zero::JavaRef<jobject>& p6,
    const ::jni_zero::JavaRef<jobject>& p7,
    const ::jni_zero::JavaRef<jobject>& p8,
    const ::jni_zero::JavaRef<jobject>& p9,
    const ::jni_zero::JavaRef<jobject>& p10,
    const ::jni_zero::JavaRef<jobject>& p11,
    const ::jni_zero::JavaRef<jobject>& p12,
    const ::jni_zero::JavaRef<jobject>& p13,
    const ::jni_zero::JavaRef<jobject>& p14,
    const ::jni_zero::JavaRef<jobject>& p15,
    const ::jni_zero::JavaRef<jobject>& p16,
    const ::jni_zero::JavaRef<jobject>& p17,
    const ::jni_zero::JavaRef<jobject>& p18,
    const ::jni_zero::JavaRef<jobject>& p19) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "of",
      "(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/Map;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      p1.obj(),
      p2.obj(),
      p3.obj(),
      p4.obj(),
      p5.obj(),
      p6.obj(),
      p7.obj(),
      p8.obj(),
      p9.obj(),
      p10.obj(),
      p11.obj(),
      p12.obj(),
      p13.obj(),
      p14.obj(),
      p15.obj(),
      p16.obj(),
      p17.obj(),
      p18.obj(),
      p19.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Map_ofEntries(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobjectArray>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_util_Map_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "ofEntries",
      "([Ljava/util/Map$Entry;)Ljava/util/Map;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}



}  // namespace JNI_Map

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::JNI_Map;

template<>
class _CalledByNativesStatics<::java::util::JMap<jobject, jobject>> {
  public:
  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JMap<K, V>> copyOf(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::util::JMap<K, V>>& p0) {
    return Java_Map_copyOf(env, p0)
        .template As<::java::util::JMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JMap_Entry<K, V>> entry(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1) {
    return Java_Map_entry(env, p0, p1)
        .template As<::java::util::JMap_Entry<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JMap<K, V>> of(JNIEnv* env) {
    return Java_Map_of(env)
        .template As<::java::util::JMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JMap<K, V>> of(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1) {
    return Java_Map_of(env, p0, p1)
        .template As<::java::util::JMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JMap<K, V>> of(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1,
      const ::jni_zero::JavaRef<K>& p2,
      const ::jni_zero::JavaRef<V>& p3) {
    return Java_Map_of(env, p0, p1, p2, p3)
        .template As<::java::util::JMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JMap<K, V>> of(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1,
      const ::jni_zero::JavaRef<K>& p2,
      const ::jni_zero::JavaRef<V>& p3,
      const ::jni_zero::JavaRef<K>& p4,
      const ::jni_zero::JavaRef<V>& p5) {
    return Java_Map_of(env, p0, p1, p2, p3, p4, p5)
        .template As<::java::util::JMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JMap<K, V>> of(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1,
      const ::jni_zero::JavaRef<K>& p2,
      const ::jni_zero::JavaRef<V>& p3,
      const ::jni_zero::JavaRef<K>& p4,
      const ::jni_zero::JavaRef<V>& p5,
      const ::jni_zero::JavaRef<K>& p6,
      const ::jni_zero::JavaRef<V>& p7) {
    return Java_Map_of(env, p0, p1, p2, p3, p4, p5, p6, p7)
        .template As<::java::util::JMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JMap<K, V>> of(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1,
      const ::jni_zero::JavaRef<K>& p2,
      const ::jni_zero::JavaRef<V>& p3,
      const ::jni_zero::JavaRef<K>& p4,
      const ::jni_zero::JavaRef<V>& p5,
      const ::jni_zero::JavaRef<K>& p6,
      const ::jni_zero::JavaRef<V>& p7,
      const ::jni_zero::JavaRef<K>& p8,
      const ::jni_zero::JavaRef<V>& p9) {
    return Java_Map_of(env, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9)
        .template As<::java::util::JMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JMap<K, V>> of(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1,
      const ::jni_zero::JavaRef<K>& p2,
      const ::jni_zero::JavaRef<V>& p3,
      const ::jni_zero::JavaRef<K>& p4,
      const ::jni_zero::JavaRef<V>& p5,
      const ::jni_zero::JavaRef<K>& p6,
      const ::jni_zero::JavaRef<V>& p7,
      const ::jni_zero::JavaRef<K>& p8,
      const ::jni_zero::JavaRef<V>& p9,
      const ::jni_zero::JavaRef<K>& p10,
      const ::jni_zero::JavaRef<V>& p11) {
    return Java_Map_of(env, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11)
        .template As<::java::util::JMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JMap<K, V>> of(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1,
      const ::jni_zero::JavaRef<K>& p2,
      const ::jni_zero::JavaRef<V>& p3,
      const ::jni_zero::JavaRef<K>& p4,
      const ::jni_zero::JavaRef<V>& p5,
      const ::jni_zero::JavaRef<K>& p6,
      const ::jni_zero::JavaRef<V>& p7,
      const ::jni_zero::JavaRef<K>& p8,
      const ::jni_zero::JavaRef<V>& p9,
      const ::jni_zero::JavaRef<K>& p10,
      const ::jni_zero::JavaRef<V>& p11,
      const ::jni_zero::JavaRef<K>& p12,
      const ::jni_zero::JavaRef<V>& p13) {
    return Java_Map_of(env, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13)
        .template As<::java::util::JMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JMap<K, V>> of(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1,
      const ::jni_zero::JavaRef<K>& p2,
      const ::jni_zero::JavaRef<V>& p3,
      const ::jni_zero::JavaRef<K>& p4,
      const ::jni_zero::JavaRef<V>& p5,
      const ::jni_zero::JavaRef<K>& p6,
      const ::jni_zero::JavaRef<V>& p7,
      const ::jni_zero::JavaRef<K>& p8,
      const ::jni_zero::JavaRef<V>& p9,
      const ::jni_zero::JavaRef<K>& p10,
      const ::jni_zero::JavaRef<V>& p11,
      const ::jni_zero::JavaRef<K>& p12,
      const ::jni_zero::JavaRef<V>& p13,
      const ::jni_zero::JavaRef<K>& p14,
      const ::jni_zero::JavaRef<V>& p15) {
    return Java_Map_of(env, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15)
        .template As<::java::util::JMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JMap<K, V>> of(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1,
      const ::jni_zero::JavaRef<K>& p2,
      const ::jni_zero::JavaRef<V>& p3,
      const ::jni_zero::JavaRef<K>& p4,
      const ::jni_zero::JavaRef<V>& p5,
      const ::jni_zero::JavaRef<K>& p6,
      const ::jni_zero::JavaRef<V>& p7,
      const ::jni_zero::JavaRef<K>& p8,
      const ::jni_zero::JavaRef<V>& p9,
      const ::jni_zero::JavaRef<K>& p10,
      const ::jni_zero::JavaRef<V>& p11,
      const ::jni_zero::JavaRef<K>& p12,
      const ::jni_zero::JavaRef<V>& p13,
      const ::jni_zero::JavaRef<K>& p14,
      const ::jni_zero::JavaRef<V>& p15,
      const ::jni_zero::JavaRef<K>& p16,
      const ::jni_zero::JavaRef<V>& p17) {
    return Java_Map_of(
        env,
        p0,
        p1,
        p2,
        p3,
        p4,
        p5,
        p6,
        p7,
        p8,
        p9,
        p10,
        p11,
        p12,
        p13,
        p14,
        p15,
        p16,
        p17)
        .template As<::java::util::JMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JMap<K, V>> of(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1,
      const ::jni_zero::JavaRef<K>& p2,
      const ::jni_zero::JavaRef<V>& p3,
      const ::jni_zero::JavaRef<K>& p4,
      const ::jni_zero::JavaRef<V>& p5,
      const ::jni_zero::JavaRef<K>& p6,
      const ::jni_zero::JavaRef<V>& p7,
      const ::jni_zero::JavaRef<K>& p8,
      const ::jni_zero::JavaRef<V>& p9,
      const ::jni_zero::JavaRef<K>& p10,
      const ::jni_zero::JavaRef<V>& p11,
      const ::jni_zero::JavaRef<K>& p12,
      const ::jni_zero::JavaRef<V>& p13,
      const ::jni_zero::JavaRef<K>& p14,
      const ::jni_zero::JavaRef<V>& p15,
      const ::jni_zero::JavaRef<K>& p16,
      const ::jni_zero::JavaRef<V>& p17,
      const ::jni_zero::JavaRef<K>& p18,
      const ::jni_zero::JavaRef<V>& p19) {
    return Java_Map_of(
        env,
        p0,
        p1,
        p2,
        p3,
        p4,
        p5,
        p6,
        p7,
        p8,
        p9,
        p10,
        p11,
        p12,
        p13,
        p14,
        p15,
        p16,
        p17,
        p18,
        p19)
        .template As<::java::util::JMap<K, V>>();
  }

  template <typename K, typename V>
  static ::jni_zero::ScopedJavaLocalRef<::java::util::JMap<K, V>> ofEntries(
      JNIEnv* env,
      const ::jni_zero::JavaRef<JArray<::java::util::JMap_Entry<K, V>>>& p0) {
    return Java_Map_ofEntries(env, p0)
        .template As<::java::util::JMap<K, V>>();
  }

};

template <typename K, typename V>
class _CalledByNatives<::java::util::JMap<K, V>> {
  public:
  void clear(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    Java_Map_clear(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<V> compute(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<::java::util::function::JBiFunction<jobject, jobject, V>>& p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_compute(env, *this_obj, p0, p1)
        .template As<V>();
  }

  ::jni_zero::ScopedJavaLocalRef<V> computeIfAbsent(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<::java::util::function::JFunction<jobject, V>>& p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_computeIfAbsent(env, *this_obj, p0, p1)
        .template As<V>();
  }

  ::jni_zero::ScopedJavaLocalRef<V> computeIfPresent(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<::java::util::function::JBiFunction<jobject, jobject, V>>& p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_computeIfPresent(env, *this_obj, p0, p1)
        .template As<V>();
  }

  bool containsKey(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_containsKey(env, *this_obj, p0);
  }

  bool containsValue(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_containsValue(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JSet<::java::util::JMap_Entry<K, V>>> entrySet(
      JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_entrySet(env, *this_obj)
        .template As<::java::util::JSet<::java::util::JMap_Entry<K, V>>>();
  }

  bool equals(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_equals(env, *this_obj, p0);
  }

  void forEach(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::util::function::JBiConsumer<jobject, jobject>>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    Java_Map_forEach(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<V> get(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_get(env, *this_obj, p0)
        .template As<V>();
  }

  ::jni_zero::ScopedJavaLocalRef<V> getOrDefault(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jobject>& p0,
      const ::jni_zero::JavaRef<V>& p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_getOrDefault(env, *this_obj, p0, p1)
        .template As<V>();
  }

  int32_t hashCode(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_hashCode(env, *this_obj);
  }

  bool isEmpty(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_isEmpty(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JSet<K>> keySet(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_keySet(env, *this_obj)
        .template As<::java::util::JSet<K>>();
  }

  ::jni_zero::ScopedJavaLocalRef<V> merge(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1,
      const ::jni_zero::JavaRef<::java::util::function::JBiFunction<jobject, jobject, V>>& p2) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_merge(env, *this_obj, p0, p1, p2)
        .template As<V>();
  }

  ::jni_zero::ScopedJavaLocalRef<V> put(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_put(env, *this_obj, p0, p1)
        .template As<V>();
  }

  void putAll(JNIEnv* env, const ::jni_zero::JavaRef<::java::util::JMap<K, V>>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    Java_Map_putAll(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<V> putIfAbsent(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_putIfAbsent(env, *this_obj, p0, p1)
        .template As<V>();
  }

  bool remove(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jobject>& p0,
      const ::jni_zero::JavaRef<jobject>& p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_remove(env, *this_obj, p0, p1);
  }

  ::jni_zero::ScopedJavaLocalRef<V> remove(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_remove(env, *this_obj, p0)
        .template As<V>();
  }

  bool replace(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1,
      const ::jni_zero::JavaRef<V>& p2) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_replace(env, *this_obj, p0, p1, p2);
  }

  ::jni_zero::ScopedJavaLocalRef<V> replace(
      JNIEnv* env,
      const ::jni_zero::JavaRef<K>& p0,
      const ::jni_zero::JavaRef<V>& p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_replace(env, *this_obj, p0, p1)
        .template As<V>();
  }

  void replaceAll(
      JNIEnv* env,
      const ::jni_zero::JavaRef<::java::util::function::JBiFunction<jobject, jobject, V>>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    Java_Map_replaceAll(env, *this_obj, p0);
  }

  int32_t size(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_size(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<::java::util::JCollection<V>> values(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<::java::util::JMap<K, V>>*>(this);
    return Java_Map_values(env, *this_obj)
        .template As<::java::util::JCollection<V>>();
  }

};


}  // namespace jni_zero_internal

namespace java::util {
using MapJni = ::jni_zero_internal::_CalledByNativesStatics<::java::util::JMap<jobject, jobject>>;
}
#ifndef _JNI_ZERO_MapJni_DEFINED
#define _JNI_ZERO_MapJni_DEFINED
using ::java::util::MapJni;
#endif


#pragma clang diagnostic pop
#endif  // java_util_Map_JNI
