// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.Object

#ifndef java_lang_Object_JNI
#define java_lang_Object_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "Object_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"
namespace JNI_Object {

// Native to Java functions
[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Object_Constructor(
    JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_object_class;
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "()V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Object_clone(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_object_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "clone",
      "()Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static bool Java_Object_equals(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_object_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "equals",
      "(Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static void Java_Object_finalize(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_object_class;
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "finalize",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jclass> Java_Object_getClass(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_object_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getClass",
      "()Ljava/lang/Class;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jclass _ret2 = static_cast<jclass>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jclass>::Adopt(env, _ret2);
}

[[maybe_unused]] static int32_t Java_Object_hashCode(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_object_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "hashCode",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static void Java_Object_notify(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_object_class;
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "notify",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}

[[maybe_unused]] static void Java_Object_notifyAll(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_object_class;
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "notifyAll",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Object_toString(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_object_class;
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "toString",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static void Java_Object_wait(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_object_class;
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "wait",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}

[[maybe_unused]] static void Java_Object_wait(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    int64_t p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_object_class;
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "wait",
      "(J)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0);
}

[[maybe_unused]] static void Java_Object_wait(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    int64_t p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = jni_zero::g_object_class;
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "wait",
      "(JI)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0, as_jint(p1));
}



}  // namespace JNI_Object

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::JNI_Object;

template<>
class _CalledByNativesStatics<jobject> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<jobject> New(JNIEnv* env) {
    return Java_Object_Constructor(env)
        .As<jobject>();
  }

};

template<>
class _CalledByNatives<jobject> {
  public:
  ::jni_zero::ScopedJavaLocalRef<jobject> clone(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jobject>*>(this);
    return Java_Object_clone(env, *this_obj);
  }

  bool equals(JNIEnv* env, const ::jni_zero::JavaRef<jobject>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jobject>*>(this);
    return Java_Object_equals(env, *this_obj, p0);
  }

  void finalize(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jobject>*>(this);
    Java_Object_finalize(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<jclass> getClass(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jobject>*>(this);
    return Java_Object_getClass(env, *this_obj);
  }

  int32_t hashCode(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jobject>*>(this);
    return Java_Object_hashCode(env, *this_obj);
  }

  void notify(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jobject>*>(this);
    Java_Object_notify(env, *this_obj);
  }

  void notifyAll(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jobject>*>(this);
    Java_Object_notifyAll(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<jstring> toString(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jobject>*>(this);
    return Java_Object_toString(env, *this_obj);
  }

  void wait(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jobject>*>(this);
    Java_Object_wait(env, *this_obj);
  }

  void wait(JNIEnv* env, int64_t p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jobject>*>(this);
    Java_Object_wait(env, *this_obj, p0);
  }

  void wait(JNIEnv* env, int64_t p0, JniIntWrapper p1) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jobject>*>(this);
    Java_Object_wait(env, *this_obj, p0, p1);
  }

};


}  // namespace jni_zero_internal

namespace java::lang {
using ObjectJni = ::jni_zero_internal::_CalledByNativesStatics<jobject>;
}
#ifndef _JNI_ZERO_ObjectJni_DEFINED
#define _JNI_ZERO_ObjectJni_DEFINED
using ::java::lang::ObjectJni;
#endif


#pragma clang diagnostic pop
#endif  // java_lang_Object_JNI
