// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.Object

#ifndef java_lang_Object_SHARED_JNI
#define java_lang_Object_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:

#endif  // java_lang_Object_SHARED_JNI
