// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     android.os.Process

#ifndef android_os_Process_SHARED_JNI
#define android_os_Process_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_android_os_JProcess_DEFINED
#define _JNI_ZERO_android_os_JProcess_DEFINED
namespace android::os {
class _JProcess : public _jobject {};
using JProcess = _JProcess*;
}
#endif

#ifndef _JNI_ZERO_JProcess_DEFINED
#define _JNI_ZERO_JProcess_DEFINED
using ::android::os::JProcess;
#endif

#ifndef _JNI_ZERO_android_os_JUserHandle_DEFINED
#define _JNI_ZERO_android_os_JUserHandle_DEFINED
namespace android::os {
class _JUserHandle : public _jobject {};
using JUserHandle = _JUserHandle*;
}
#endif

#ifndef _JNI_ZERO_JUserHandle_DEFINED
#define _JNI_ZERO_JUserHandle_DEFINED
using ::android::os::JUserHandle;
#endif


#endif  // android_os_Process_SHARED_JNI
