// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     android.os.Process

#ifndef android_os_Process_JNI
#define android_os_Process_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "Process_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Class Accessors
#ifndef android_os_Process_clazz_defined
#define android_os_Process_clazz_defined
inline jclass android_os_Process_clazz(JNIEnv* env) {
  static const char kClassName[] = "android.os.Process";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace JNI_Process {

// Native to Java functions
[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Process_Constructor(
    JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "()V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static int32_t Java_Process_getAppUidForSdkSandboxUid(
    JNIEnv* env,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getAppUidForSdkSandboxUid",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static int64_t Java_Process_getElapsedCpuTime(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getElapsedCpuTime",
      "()J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jintArray> Java_Process_getExclusiveCores(
    JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getExclusiveCores",
      "()[I",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id());
  jintArray _ret2 = static_cast<jintArray>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jintArray>::Adopt(env, _ret2);
}

[[maybe_unused]] static int32_t Java_Process_getGidForName(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getGidForName",
      "(Ljava/lang/String;)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Process_getSdkSandboxUidForAppUid(
    JNIEnv* env,
    JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getSdkSandboxUidForAppUid",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static int64_t Java_Process_getStartElapsedRealtime(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getStartElapsedRealtime",
      "()J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int64_t Java_Process_getStartRequestedElapsedRealtime(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getStartRequestedElapsedRealtime",
      "()J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int64_t Java_Process_getStartRequestedUptimeMillis(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getStartRequestedUptimeMillis",
      "()J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int64_t Java_Process_getStartUptimeMillis(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getStartUptimeMillis",
      "()J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Process_getThreadPriority(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getThreadPriority",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static int32_t Java_Process_getUidForName(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getUidForName",
      "(Ljava/lang/String;)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static bool Java_Process_is64Bit(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "is64Bit",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id());
  return _ret;
}

[[maybe_unused]] static bool Java_Process_isApplicationUid(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "isApplicationUid",
      "(I)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static bool Java_Process_isIsolated(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "isIsolated",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id());
  return _ret;
}

[[maybe_unused]] static bool Java_Process_isIsolatedUid(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "isIsolatedUid",
      "(I)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static bool Java_Process_isPrivateComputeCoreUid(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "isPrivateComputeCoreUid",
      "(I)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static bool Java_Process_isSdkSandbox(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "isSdkSandbox",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id());
  return _ret;
}

[[maybe_unused]] static bool Java_Process_isSdkSandboxUid(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "isSdkSandboxUid",
      "(I)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static void Java_Process_killProcess(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "killProcess",
      "(I)V",
      &cached_method_id);
  env->CallStaticVoidMethod(clazz, call_context.method_id(), as_jint(p0));
}

[[maybe_unused]] static int32_t Java_Process_myPid(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "myPid",
      "()I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Process_myProcessName(
    JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "myProcessName",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static int32_t Java_Process_myTid(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "myTid",
      "()I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id());
  return _ret;
}

[[maybe_unused]] static int32_t Java_Process_myUid(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "myUid",
      "()I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id());
  return _ret;
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobject> Java_Process_myUserHandle(
    JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "myUserHandle",
      "()Landroid/os/UserHandle;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id());
  return ::jni_zero::ScopedJavaLocalRef<jobject>::Adopt(env, _ret);
}

[[maybe_unused]] static void Java_Process_sendSignal(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "sendSignal",
      "(II)V",
      &cached_method_id);
  env->CallStaticVoidMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
}

[[maybe_unused]] static void Java_Process_setThreadPriority(JNIEnv* env, JniIntWrapper p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "setThreadPriority",
      "(I)V",
      &cached_method_id);
  env->CallStaticVoidMethod(clazz, call_context.method_id(), as_jint(p0));
}

[[maybe_unused]] static void Java_Process_setThreadPriority(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "setThreadPriority",
      "(II)V",
      &cached_method_id);
  env->CallStaticVoidMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
}

[[maybe_unused]] static bool Java_Process_supportsProcesses(JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = android_os_Process_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "supportsProcesses",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id());
  return _ret;
}



}  // namespace JNI_Process

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::JNI_Process;

template<>
class _CalledByNativesStatics<::android::os::JProcess> {
  public:
  static inline constexpr int32_t BLUETOOTH_UID = 1002;
  static inline constexpr int32_t FIRST_APPLICATION_UID = 10000;
  static inline constexpr int32_t INVALID_PID = -1;
  static inline constexpr int32_t INVALID_UID = -1;
  static inline constexpr int32_t LAST_APPLICATION_UID = 19999;
  static inline constexpr int32_t PHONE_UID = 1001;
  static inline constexpr int32_t ROOT_UID = 0;
  static inline constexpr int32_t SHELL_UID = 2000;
  static inline constexpr int32_t SIGNAL_KILL = 9;
  static inline constexpr int32_t SIGNAL_QUIT = 3;
  static inline constexpr int32_t SIGNAL_USR1 = 10;
  static inline constexpr int32_t SYSTEM_UID = 1000;
  static inline constexpr int32_t THREAD_PRIORITY_AUDIO = -16;
  static inline constexpr int32_t THREAD_PRIORITY_BACKGROUND = 10;
  static inline constexpr int32_t THREAD_PRIORITY_DEFAULT = 0;
  static inline constexpr int32_t THREAD_PRIORITY_DISPLAY = -4;
  static inline constexpr int32_t THREAD_PRIORITY_FOREGROUND = -2;
  static inline constexpr int32_t THREAD_PRIORITY_LESS_FAVORABLE = 1;
  static inline constexpr int32_t THREAD_PRIORITY_LOWEST = 19;
  static inline constexpr int32_t THREAD_PRIORITY_MORE_FAVORABLE = -1;
  static inline constexpr int32_t THREAD_PRIORITY_URGENT_AUDIO = -19;
  static inline constexpr int32_t THREAD_PRIORITY_URGENT_DISPLAY = -8;
  static inline constexpr int32_t THREAD_PRIORITY_VIDEO = -10;
  static inline constexpr int32_t WIFI_UID = 1010;
  static int32_t Get_BLUETOOTH_UID(JNIEnv* env) {
    return 1002;
  }
  static int32_t Get_FIRST_APPLICATION_UID(JNIEnv* env) {
    return 10000;
  }
  static int32_t Get_INVALID_PID(JNIEnv* env) {
    return -1;
  }
  static int32_t Get_INVALID_UID(JNIEnv* env) {
    return -1;
  }
  static int32_t Get_LAST_APPLICATION_UID(JNIEnv* env) {
    return 19999;
  }
  static int32_t Get_PHONE_UID(JNIEnv* env) {
    return 1001;
  }
  static int32_t Get_ROOT_UID(JNIEnv* env) {
    return 0;
  }
  static int32_t Get_SHELL_UID(JNIEnv* env) {
    return 2000;
  }
  static int32_t Get_SIGNAL_KILL(JNIEnv* env) {
    return 9;
  }
  static int32_t Get_SIGNAL_QUIT(JNIEnv* env) {
    return 3;
  }
  static int32_t Get_SIGNAL_USR1(JNIEnv* env) {
    return 10;
  }
  static int32_t Get_SYSTEM_UID(JNIEnv* env) {
    return 1000;
  }
  static int32_t Get_THREAD_PRIORITY_AUDIO(JNIEnv* env) {
    return -16;
  }
  static int32_t Get_THREAD_PRIORITY_BACKGROUND(JNIEnv* env) {
    return 10;
  }
  static int32_t Get_THREAD_PRIORITY_DEFAULT(JNIEnv* env) {
    return 0;
  }
  static int32_t Get_THREAD_PRIORITY_DISPLAY(JNIEnv* env) {
    return -4;
  }
  static int32_t Get_THREAD_PRIORITY_FOREGROUND(JNIEnv* env) {
    return -2;
  }
  static int32_t Get_THREAD_PRIORITY_LESS_FAVORABLE(JNIEnv* env) {
    return 1;
  }
  static int32_t Get_THREAD_PRIORITY_LOWEST(JNIEnv* env) {
    return 19;
  }
  static int32_t Get_THREAD_PRIORITY_MORE_FAVORABLE(JNIEnv* env) {
    return -1;
  }
  static int32_t Get_THREAD_PRIORITY_URGENT_AUDIO(JNIEnv* env) {
    return -19;
  }
  static int32_t Get_THREAD_PRIORITY_URGENT_DISPLAY(JNIEnv* env) {
    return -8;
  }
  static int32_t Get_THREAD_PRIORITY_VIDEO(JNIEnv* env) {
    return -10;
  }
  static int32_t Get_WIFI_UID(JNIEnv* env) {
    return 1010;
  }
  static ::jni_zero::ScopedJavaLocalRef<::android::os::JProcess> New(JNIEnv* env) {
    return Java_Process_Constructor(env)
        .As<::android::os::JProcess>();
  }

  static int32_t getAppUidForSdkSandboxUid(JNIEnv* env, JniIntWrapper p0) {
    return Java_Process_getAppUidForSdkSandboxUid(env, p0);
  }

  static int64_t getElapsedCpuTime(JNIEnv* env) {
    return Java_Process_getElapsedCpuTime(env);
  }

  static ::jni_zero::ScopedJavaLocalRef<JArray<int32_t>> getExclusiveCores(JNIEnv* env) {
    return Java_Process_getExclusiveCores(env)
        .As<JArray<int32_t>>();
  }

  static int32_t getGidForName(JNIEnv* env, const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Process_getGidForName(env, p0);
  }

  static int32_t getSdkSandboxUidForAppUid(JNIEnv* env, JniIntWrapper p0) {
    return Java_Process_getSdkSandboxUidForAppUid(env, p0);
  }

  static int64_t getStartElapsedRealtime(JNIEnv* env) {
    return Java_Process_getStartElapsedRealtime(env);
  }

  static int64_t getStartRequestedElapsedRealtime(JNIEnv* env) {
    return Java_Process_getStartRequestedElapsedRealtime(env);
  }

  static int64_t getStartRequestedUptimeMillis(JNIEnv* env) {
    return Java_Process_getStartRequestedUptimeMillis(env);
  }

  static int64_t getStartUptimeMillis(JNIEnv* env) {
    return Java_Process_getStartUptimeMillis(env);
  }

  static int32_t getThreadPriority(JNIEnv* env, JniIntWrapper p0) {
    return Java_Process_getThreadPriority(env, p0);
  }

  static int32_t getUidForName(JNIEnv* env, const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Process_getUidForName(env, p0);
  }

  static bool is64Bit(JNIEnv* env) {
    return Java_Process_is64Bit(env);
  }

  static bool isApplicationUid(JNIEnv* env, JniIntWrapper p0) {
    return Java_Process_isApplicationUid(env, p0);
  }

  static bool isIsolated(JNIEnv* env) {
    return Java_Process_isIsolated(env);
  }

  static bool isIsolatedUid(JNIEnv* env, JniIntWrapper p0) {
    return Java_Process_isIsolatedUid(env, p0);
  }

  static bool isPrivateComputeCoreUid(JNIEnv* env, JniIntWrapper p0) {
    return Java_Process_isPrivateComputeCoreUid(env, p0);
  }

  static bool isSdkSandbox(JNIEnv* env) {
    return Java_Process_isSdkSandbox(env);
  }

  static bool isSdkSandboxUid(JNIEnv* env, JniIntWrapper p0) {
    return Java_Process_isSdkSandboxUid(env, p0);
  }

  static void killProcess(JNIEnv* env, JniIntWrapper p0) {
    Java_Process_killProcess(env, p0);
  }

  static int32_t myPid(JNIEnv* env) {
    return Java_Process_myPid(env);
  }

  static ::jni_zero::ScopedJavaLocalRef<jstring> myProcessName(JNIEnv* env) {
    return Java_Process_myProcessName(env);
  }

  static int32_t myTid(JNIEnv* env) {
    return Java_Process_myTid(env);
  }

  static int32_t myUid(JNIEnv* env) {
    return Java_Process_myUid(env);
  }

  static ::jni_zero::ScopedJavaLocalRef<::android::os::JUserHandle> myUserHandle(JNIEnv* env) {
    return Java_Process_myUserHandle(env)
        .As<::android::os::JUserHandle>();
  }

  static void sendSignal(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
    Java_Process_sendSignal(env, p0, p1);
  }

  static void setThreadPriority(JNIEnv* env, JniIntWrapper p0) {
    Java_Process_setThreadPriority(env, p0);
  }

  static void setThreadPriority(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
    Java_Process_setThreadPriority(env, p0, p1);
  }

  static bool supportsProcesses(JNIEnv* env) {
    return Java_Process_supportsProcesses(env);
  }

};


}  // namespace jni_zero_internal

namespace android::os {
using ProcessJni = ::jni_zero_internal::_CalledByNativesStatics<::android::os::JProcess>;
}
#ifndef _JNI_ZERO_ProcessJni_DEFINED
#define _JNI_ZERO_ProcessJni_DEFINED
using ::android::os::ProcessJni;
#endif


#pragma clang diagnostic pop
#endif  // android_os_Process_JNI
