// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.Runnable

#ifndef java_lang_Runnable_SHARED_JNI
#define java_lang_Runnable_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_lang_JRunnable_DEFINED
#define _JNI_ZERO_java_lang_JRunnable_DEFINED
namespace java::lang {
class _JRunnable : public _jobject {};
using JRunnable = _JRunnable*;
}
#endif

#ifndef _JNI_ZERO_JRunnable_DEFINED
#define _JNI_ZERO_JRunnable_DEFINED
using ::java::lang::JRunnable;
#endif


#endif  // java_lang_Runnable_SHARED_JNI
