// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.Runtime

#ifndef java_lang_Runtime_SHARED_JNI
#define java_lang_Runtime_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_io_JFile_DEFINED
#define _JNI_ZERO_java_io_JFile_DEFINED
namespace java::io {
class _JFile : public _jobject {};
using JFile = _JFile*;
}
#endif

#ifndef _JNI_ZERO_JFile_DEFINED
#define _JNI_ZERO_JFile_DEFINED
using ::java::io::JFile;
#endif

#ifndef _JNI_ZERO_java_lang_JProcess_DEFINED
#define _JNI_ZERO_java_lang_JProcess_DEFINED
namespace java::lang {
class _JProcess : public _jobject {};
using JProcess = _JProcess*;
}
#endif

#ifndef _JNI_ZERO_JProcess_DEFINED
#define _JNI_ZERO_JProcess_DEFINED
using ::java::lang::JProcess;
#endif

#ifndef _JNI_ZERO_java_lang_JRuntime_DEFINED
#define _JNI_ZERO_java_lang_JRuntime_DEFINED
namespace java::lang {
class _JRuntime : public _jobject {};
using JRuntime = _JRuntime*;
}
#endif

#ifndef _JNI_ZERO_JRuntime_DEFINED
#define _JNI_ZERO_JRuntime_DEFINED
using ::java::lang::JRuntime;
#endif

#ifndef _JNI_ZERO_java_lang_JThread_DEFINED
#define _JNI_ZERO_java_lang_JThread_DEFINED
namespace java::lang {
class _JThread : public _jobject {};
using JThread = _JThread*;
}
#endif

#ifndef _JNI_ZERO_JThread_DEFINED
#define _JNI_ZERO_JThread_DEFINED
using ::java::lang::JThread;
#endif


#endif  // java_lang_Runtime_SHARED_JNI
