// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.Throwable

#ifndef java_lang_Throwable_SHARED_JNI
#define java_lang_Throwable_SHARED_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_zero_internal.h"

// Relevant jobject subclasses:
#ifndef _JNI_ZERO_java_io_JPrintStream_DEFINED
#define _JNI_ZERO_java_io_JPrintStream_DEFINED
namespace java::io {
class _JPrintStream : public _jobject {};
using JPrintStream = _JPrintStream*;
}
#endif

#ifndef _JNI_ZERO_JPrintStream_DEFINED
#define _JNI_ZERO_JPrintStream_DEFINED
using ::java::io::JPrintStream;
#endif

#ifndef _JNI_ZERO_java_io_JPrintWriter_DEFINED
#define _JNI_ZERO_java_io_JPrintWriter_DEFINED
namespace java::io {
class _JPrintWriter : public _jobject {};
using JPrintWriter = _JPrintWriter*;
}
#endif

#ifndef _JNI_ZERO_JPrintWriter_DEFINED
#define _JNI_ZERO_JPrintWriter_DEFINED
using ::java::io::JPrintWriter;
#endif

#ifndef _JNI_ZERO_java_lang_JStackTraceElement_DEFINED
#define _JNI_ZERO_java_lang_JStackTraceElement_DEFINED
namespace java::lang {
class _JStackTraceElement : public _jobject {};
using JStackTraceElement = _JStackTraceElement*;
}
#endif

#ifndef _JNI_ZERO_JStackTraceElement_DEFINED
#define _JNI_ZERO_JStackTraceElement_DEFINED
using ::java::lang::JStackTraceElement;
#endif


#endif  // java_lang_Throwable_SHARED_JNI
