// This file was generated by
//     //third_party/jni_zero/jni_zero.py
// For
//     java.lang.Throwable

#ifndef java_lang_Throwable_JNI
#define java_lang_Throwable_JNI

#include <jni.h>
#include <utility>

#include "third_party/jni_zero/jni_zero_internal.h"
#include "Throwable_shared_jni.h"

// Field, class, and method accessors use inline functions with static
// variables for caching.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunique-object-duplication"

// Class Accessors
#ifndef java_lang_StackTraceElement_clazz_defined
#define java_lang_StackTraceElement_clazz_defined
inline jclass java_lang_StackTraceElement_clazz(JNIEnv* env) {
  static const char kClassName[] = "java.lang.StackTraceElement";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

#ifndef java_lang_Throwable_clazz_defined
#define java_lang_Throwable_clazz_defined
inline jclass java_lang_Throwable_clazz(JNIEnv* env) {
  static const char kClassName[] = "java.lang.Throwable";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace JNI_Throwable {

// Native to Java functions
[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jthrowable> Java_Throwable_Constructor(
    JNIEnv* env) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "()V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id());
  jthrowable _ret2 = static_cast<jthrowable>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jthrowable>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jthrowable> Java_Throwable_Constructor__String(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/lang/String;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0.obj());
  jthrowable _ret2 = static_cast<jthrowable>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jthrowable>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jthrowable> Java_Throwable_Constructor(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0,
    const ::jni_zero::JavaRef<jthrowable>& p1) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/lang/String;Ljava/lang/Throwable;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0.obj(), p1.obj());
  jthrowable _ret2 = static_cast<jthrowable>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jthrowable>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jthrowable> Java_Throwable_Constructor(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jstring>& p0,
    const ::jni_zero::JavaRef<jthrowable>& p1,
    bool p2,
    bool p3) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/lang/String;Ljava/lang/Throwable;ZZ)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0.obj(), p1.obj(), p2, p3);
  jthrowable _ret2 = static_cast<jthrowable>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jthrowable>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jthrowable> Java_Throwable_Constructor__Throwable(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jthrowable>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/lang/Throwable;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0.obj());
  jthrowable _ret2 = static_cast<jthrowable>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jthrowable>::Adopt(env, _ret2);
}

[[maybe_unused]] static void Java_Throwable_addSuppressed(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jthrowable>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "addSuppressed",
      "(Ljava/lang/Throwable;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0.obj());
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jthrowable> Java_Throwable_fillInStackTrace(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "fillInStackTrace",
      "()Ljava/lang/Throwable;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jthrowable _ret2 = static_cast<jthrowable>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jthrowable>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jthrowable> Java_Throwable_getCause(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getCause",
      "()Ljava/lang/Throwable;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jthrowable _ret2 = static_cast<jthrowable>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jthrowable>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Throwable_getLocalizedMessage(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getLocalizedMessage",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Throwable_getMessage(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getMessage",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobjectArray> Java_Throwable_getStackTrace(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getStackTrace",
      "()[Ljava/lang/StackTraceElement;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jobjectArray _ret2 = static_cast<jobjectArray>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jobjectArray>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jobjectArray> Java_Throwable_getSuppressed(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getSuppressed",
      "()[Ljava/lang/Throwable;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jobjectArray _ret2 = static_cast<jobjectArray>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jobjectArray>::Adopt(env, _ret2);
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jthrowable> Java_Throwable_initCause(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jthrowable>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "initCause",
      "(Ljava/lang/Throwable;)Ljava/lang/Throwable;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id(), p0.obj());
  jthrowable _ret2 = static_cast<jthrowable>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jthrowable>::Adopt(env, _ret2);
}

[[maybe_unused]] static void Java_Throwable_printStackTrace(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "printStackTrace",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}

[[maybe_unused]] static void Java_Throwable_printStackTrace__java_io_PrintStream(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "printStackTrace",
      "(Ljava/io/PrintStream;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0.obj());
}

[[maybe_unused]] static void Java_Throwable_printStackTrace__java_io_PrintWriter(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobject>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "printStackTrace",
      "(Ljava/io/PrintWriter;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0.obj());
}

[[maybe_unused]] static void Java_Throwable_setStackTrace(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj,
    const ::jni_zero::JavaRef<jobjectArray>& p0) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "setStackTrace",
      "([Ljava/lang/StackTraceElement;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0.obj());
}

[[maybe_unused]] static ::jni_zero::ScopedJavaLocalRef<jstring> Java_Throwable_toString(
    JNIEnv* env,
    const ::jni_zero::JavaRef<jobject>& obj) {
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Throwable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  ::jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<::jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "toString",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return ::jni_zero::ScopedJavaLocalRef<jstring>::Adopt(env, _ret2);
}



}  // namespace JNI_Throwable

// jobject-subclass-aware definitions:
namespace jni_zero_internal {

using namespace ::JNI_Throwable;

template<>
class _CalledByNativesStatics<jthrowable> {
  public:
  static ::jni_zero::ScopedJavaLocalRef<jthrowable> New(JNIEnv* env) {
    return Java_Throwable_Constructor(env)
        .As<jthrowable>();
  }

  static ::jni_zero::ScopedJavaLocalRef<jthrowable> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0) {
    return Java_Throwable_Constructor__String(env, p0)
        .As<jthrowable>();
  }

  static ::jni_zero::ScopedJavaLocalRef<jthrowable> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0,
      const ::jni_zero::JavaRef<jthrowable>& p1) {
    return Java_Throwable_Constructor(env, p0, p1)
        .As<jthrowable>();
  }

  static ::jni_zero::ScopedJavaLocalRef<jthrowable> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jstring>& p0,
      const ::jni_zero::JavaRef<jthrowable>& p1,
      bool p2,
      bool p3) {
    return Java_Throwable_Constructor(env, p0, p1, p2, p3)
        .As<jthrowable>();
  }

  static ::jni_zero::ScopedJavaLocalRef<jthrowable> New(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jthrowable>& p0) {
    return Java_Throwable_Constructor__Throwable(env, p0)
        .As<jthrowable>();
  }

};

template<>
class _CalledByNatives<jthrowable> {
  public:
  void addSuppressed(JNIEnv* env, const ::jni_zero::JavaRef<jthrowable>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jthrowable>*>(this);
    Java_Throwable_addSuppressed(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<jthrowable> fillInStackTrace(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jthrowable>*>(this);
    return Java_Throwable_fillInStackTrace(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<jthrowable> getCause(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jthrowable>*>(this);
    return Java_Throwable_getCause(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<jstring> getLocalizedMessage(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jthrowable>*>(this);
    return Java_Throwable_getLocalizedMessage(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<jstring> getMessage(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jthrowable>*>(this);
    return Java_Throwable_getMessage(env, *this_obj);
  }

  ::jni_zero::ScopedJavaLocalRef<JArray<::java::lang::JStackTraceElement>> getStackTrace(
      JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jthrowable>*>(this);
    return Java_Throwable_getStackTrace(env, *this_obj)
        .As<JArray<::java::lang::JStackTraceElement>>();
  }

  ::jni_zero::ScopedJavaLocalRef<JArray<jthrowable>> getSuppressed(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jthrowable>*>(this);
    return Java_Throwable_getSuppressed(env, *this_obj)
        .As<JArray<jthrowable>>();
  }

  ::jni_zero::ScopedJavaLocalRef<jthrowable> initCause(
      JNIEnv* env,
      const ::jni_zero::JavaRef<jthrowable>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jthrowable>*>(this);
    return Java_Throwable_initCause(env, *this_obj, p0);
  }

  void printStackTrace(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jthrowable>*>(this);
    Java_Throwable_printStackTrace(env, *this_obj);
  }

  void printStackTrace(JNIEnv* env, const ::jni_zero::JavaRef<::java::io::JPrintStream>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jthrowable>*>(this);
    Java_Throwable_printStackTrace__java_io_PrintStream(env, *this_obj, p0);
  }

  void printStackTrace(JNIEnv* env, const ::jni_zero::JavaRef<::java::io::JPrintWriter>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jthrowable>*>(this);
    Java_Throwable_printStackTrace__java_io_PrintWriter(env, *this_obj, p0);
  }

  void setStackTrace(
      JNIEnv* env,
      const ::jni_zero::JavaRef<JArray<::java::lang::JStackTraceElement>>& p0) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jthrowable>*>(this);
    Java_Throwable_setStackTrace(env, *this_obj, p0);
  }

  ::jni_zero::ScopedJavaLocalRef<jstring> toString(JNIEnv* env) const {
    auto this_obj = reinterpret_cast<const ::jni_zero::JavaRef<jthrowable>*>(this);
    return Java_Throwable_toString(env, *this_obj);
  }

};


}  // namespace jni_zero_internal

namespace java::lang {
using ThrowableJni = ::jni_zero_internal::_CalledByNativesStatics<jthrowable>;
}
#ifndef _JNI_ZERO_ThrowableJni_DEFINED
#define _JNI_ZERO_ThrowableJni_DEFINED
using ::java::lang::ThrowableJni;
#endif


#pragma clang diagnostic pop
#endif  // java_lang_Throwable_JNI
